/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './source/__root'
import { Route as AgentIndexRouteImport } from './source/agent/index'
import { Route as AgentFip6DossiersRejetASignerRouteImport } from './source/agent/fip6/dossiers/rejet-a-signer'
import { Route as AgentFip6DossiersPropositionASignerRouteImport } from './source/agent/fip6/dossiers/proposition-a-signer'
import { Route as AgentFip6DossiersEnAttenteIndemnisationRouteImport } from './source/agent/fip6/dossiers/en-attente-indemnisation'
import { Route as AgentFip6DossiersArreteASignerRouteImport } from './source/agent/fip6/dossiers/arrete-a-signer'
import { Route as AgentFip6DossiersAVerifierRouteImport } from './source/agent/fip6/dossiers/a-verifier'
import { Route as AgentFip6DossiersATransmettreRouteImport } from './source/agent/fip6/dossiers/a-transmettre'
import { Route as AgentFip6DossiersAInstruireRouteImport } from './source/agent/fip6/dossiers/a-instruire'
import { Route as AgentFip6DossiersAAttribuerRouteImport } from './source/agent/fip6/dossiers/a-attribuer'

const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentFip6DossiersRejetASignerRoute =
  AgentFip6DossiersRejetASignerRouteImport.update({
    id: '/agent/fip6/dossiers/rejet-a-signer',
    path: '/agent/fip6/dossiers/rejet-a-signer',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip6DossiersPropositionASignerRoute =
  AgentFip6DossiersPropositionASignerRouteImport.update({
    id: '/agent/fip6/dossiers/proposition-a-signer',
    path: '/agent/fip6/dossiers/proposition-a-signer',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip6DossiersEnAttenteIndemnisationRoute =
  AgentFip6DossiersEnAttenteIndemnisationRouteImport.update({
    id: '/agent/fip6/dossiers/en-attente-indemnisation',
    path: '/agent/fip6/dossiers/en-attente-indemnisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip6DossiersArreteASignerRoute =
  AgentFip6DossiersArreteASignerRouteImport.update({
    id: '/agent/fip6/dossiers/arrete-a-signer',
    path: '/agent/fip6/dossiers/arrete-a-signer',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip6DossiersAVerifierRoute =
  AgentFip6DossiersAVerifierRouteImport.update({
    id: '/agent/fip6/dossiers/a-verifier',
    path: '/agent/fip6/dossiers/a-verifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip6DossiersATransmettreRoute =
  AgentFip6DossiersATransmettreRouteImport.update({
    id: '/agent/fip6/dossiers/a-transmettre',
    path: '/agent/fip6/dossiers/a-transmettre',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip6DossiersAInstruireRoute =
  AgentFip6DossiersAInstruireRouteImport.update({
    id: '/agent/fip6/dossiers/a-instruire',
    path: '/agent/fip6/dossiers/a-instruire',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip6DossiersAAttribuerRoute =
  AgentFip6DossiersAAttribuerRouteImport.update({
    id: '/agent/fip6/dossiers/a-attribuer',
    path: '/agent/fip6/dossiers/a-attribuer',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/agent': typeof AgentIndexRoute
  '/agent/fip6/dossiers/a-attribuer': typeof AgentFip6DossiersAAttribuerRoute
  '/agent/fip6/dossiers/a-instruire': typeof AgentFip6DossiersAInstruireRoute
  '/agent/fip6/dossiers/a-transmettre': typeof AgentFip6DossiersATransmettreRoute
  '/agent/fip6/dossiers/a-verifier': typeof AgentFip6DossiersAVerifierRoute
  '/agent/fip6/dossiers/arrete-a-signer': typeof AgentFip6DossiersArreteASignerRoute
  '/agent/fip6/dossiers/en-attente-indemnisation': typeof AgentFip6DossiersEnAttenteIndemnisationRoute
  '/agent/fip6/dossiers/proposition-a-signer': typeof AgentFip6DossiersPropositionASignerRoute
  '/agent/fip6/dossiers/rejet-a-signer': typeof AgentFip6DossiersRejetASignerRoute
}
export interface FileRoutesByTo {
  '/agent': typeof AgentIndexRoute
  '/agent/fip6/dossiers/a-attribuer': typeof AgentFip6DossiersAAttribuerRoute
  '/agent/fip6/dossiers/a-instruire': typeof AgentFip6DossiersAInstruireRoute
  '/agent/fip6/dossiers/a-transmettre': typeof AgentFip6DossiersATransmettreRoute
  '/agent/fip6/dossiers/a-verifier': typeof AgentFip6DossiersAVerifierRoute
  '/agent/fip6/dossiers/arrete-a-signer': typeof AgentFip6DossiersArreteASignerRoute
  '/agent/fip6/dossiers/en-attente-indemnisation': typeof AgentFip6DossiersEnAttenteIndemnisationRoute
  '/agent/fip6/dossiers/proposition-a-signer': typeof AgentFip6DossiersPropositionASignerRoute
  '/agent/fip6/dossiers/rejet-a-signer': typeof AgentFip6DossiersRejetASignerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/agent/': typeof AgentIndexRoute
  '/agent/fip6/dossiers/a-attribuer': typeof AgentFip6DossiersAAttribuerRoute
  '/agent/fip6/dossiers/a-instruire': typeof AgentFip6DossiersAInstruireRoute
  '/agent/fip6/dossiers/a-transmettre': typeof AgentFip6DossiersATransmettreRoute
  '/agent/fip6/dossiers/a-verifier': typeof AgentFip6DossiersAVerifierRoute
  '/agent/fip6/dossiers/arrete-a-signer': typeof AgentFip6DossiersArreteASignerRoute
  '/agent/fip6/dossiers/en-attente-indemnisation': typeof AgentFip6DossiersEnAttenteIndemnisationRoute
  '/agent/fip6/dossiers/proposition-a-signer': typeof AgentFip6DossiersPropositionASignerRoute
  '/agent/fip6/dossiers/rejet-a-signer': typeof AgentFip6DossiersRejetASignerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agent'
    | '/agent/fip6/dossiers/a-attribuer'
    | '/agent/fip6/dossiers/a-instruire'
    | '/agent/fip6/dossiers/a-transmettre'
    | '/agent/fip6/dossiers/a-verifier'
    | '/agent/fip6/dossiers/arrete-a-signer'
    | '/agent/fip6/dossiers/en-attente-indemnisation'
    | '/agent/fip6/dossiers/proposition-a-signer'
    | '/agent/fip6/dossiers/rejet-a-signer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agent'
    | '/agent/fip6/dossiers/a-attribuer'
    | '/agent/fip6/dossiers/a-instruire'
    | '/agent/fip6/dossiers/a-transmettre'
    | '/agent/fip6/dossiers/a-verifier'
    | '/agent/fip6/dossiers/arrete-a-signer'
    | '/agent/fip6/dossiers/en-attente-indemnisation'
    | '/agent/fip6/dossiers/proposition-a-signer'
    | '/agent/fip6/dossiers/rejet-a-signer'
  id:
    | '__root__'
    | '/agent/'
    | '/agent/fip6/dossiers/a-attribuer'
    | '/agent/fip6/dossiers/a-instruire'
    | '/agent/fip6/dossiers/a-transmettre'
    | '/agent/fip6/dossiers/a-verifier'
    | '/agent/fip6/dossiers/arrete-a-signer'
    | '/agent/fip6/dossiers/en-attente-indemnisation'
    | '/agent/fip6/dossiers/proposition-a-signer'
    | '/agent/fip6/dossiers/rejet-a-signer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AgentIndexRoute: typeof AgentIndexRoute
  AgentFip6DossiersAAttribuerRoute: typeof AgentFip6DossiersAAttribuerRoute
  AgentFip6DossiersAInstruireRoute: typeof AgentFip6DossiersAInstruireRoute
  AgentFip6DossiersATransmettreRoute: typeof AgentFip6DossiersATransmettreRoute
  AgentFip6DossiersAVerifierRoute: typeof AgentFip6DossiersAVerifierRoute
  AgentFip6DossiersArreteASignerRoute: typeof AgentFip6DossiersArreteASignerRoute
  AgentFip6DossiersEnAttenteIndemnisationRoute: typeof AgentFip6DossiersEnAttenteIndemnisationRoute
  AgentFip6DossiersPropositionASignerRoute: typeof AgentFip6DossiersPropositionASignerRoute
  AgentFip6DossiersRejetASignerRoute: typeof AgentFip6DossiersRejetASignerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip6/dossiers/rejet-a-signer': {
      id: '/agent/fip6/dossiers/rejet-a-signer'
      path: '/agent/fip6/dossiers/rejet-a-signer'
      fullPath: '/agent/fip6/dossiers/rejet-a-signer'
      preLoaderRoute: typeof AgentFip6DossiersRejetASignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip6/dossiers/proposition-a-signer': {
      id: '/agent/fip6/dossiers/proposition-a-signer'
      path: '/agent/fip6/dossiers/proposition-a-signer'
      fullPath: '/agent/fip6/dossiers/proposition-a-signer'
      preLoaderRoute: typeof AgentFip6DossiersPropositionASignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip6/dossiers/en-attente-indemnisation': {
      id: '/agent/fip6/dossiers/en-attente-indemnisation'
      path: '/agent/fip6/dossiers/en-attente-indemnisation'
      fullPath: '/agent/fip6/dossiers/en-attente-indemnisation'
      preLoaderRoute: typeof AgentFip6DossiersEnAttenteIndemnisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip6/dossiers/arrete-a-signer': {
      id: '/agent/fip6/dossiers/arrete-a-signer'
      path: '/agent/fip6/dossiers/arrete-a-signer'
      fullPath: '/agent/fip6/dossiers/arrete-a-signer'
      preLoaderRoute: typeof AgentFip6DossiersArreteASignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip6/dossiers/a-verifier': {
      id: '/agent/fip6/dossiers/a-verifier'
      path: '/agent/fip6/dossiers/a-verifier'
      fullPath: '/agent/fip6/dossiers/a-verifier'
      preLoaderRoute: typeof AgentFip6DossiersAVerifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip6/dossiers/a-transmettre': {
      id: '/agent/fip6/dossiers/a-transmettre'
      path: '/agent/fip6/dossiers/a-transmettre'
      fullPath: '/agent/fip6/dossiers/a-transmettre'
      preLoaderRoute: typeof AgentFip6DossiersATransmettreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip6/dossiers/a-instruire': {
      id: '/agent/fip6/dossiers/a-instruire'
      path: '/agent/fip6/dossiers/a-instruire'
      fullPath: '/agent/fip6/dossiers/a-instruire'
      preLoaderRoute: typeof AgentFip6DossiersAInstruireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip6/dossiers/a-attribuer': {
      id: '/agent/fip6/dossiers/a-attribuer'
      path: '/agent/fip6/dossiers/a-attribuer'
      fullPath: '/agent/fip6/dossiers/a-attribuer'
      preLoaderRoute: typeof AgentFip6DossiersAAttribuerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AgentIndexRoute: AgentIndexRoute,
  AgentFip6DossiersAAttribuerRoute: AgentFip6DossiersAAttribuerRoute,
  AgentFip6DossiersAInstruireRoute: AgentFip6DossiersAInstruireRoute,
  AgentFip6DossiersATransmettreRoute: AgentFip6DossiersATransmettreRoute,
  AgentFip6DossiersAVerifierRoute: AgentFip6DossiersAVerifierRoute,
  AgentFip6DossiersArreteASignerRoute: AgentFip6DossiersArreteASignerRoute,
  AgentFip6DossiersEnAttenteIndemnisationRoute:
    AgentFip6DossiersEnAttenteIndemnisationRoute,
  AgentFip6DossiersPropositionASignerRoute:
    AgentFip6DossiersPropositionASignerRoute,
  AgentFip6DossiersRejetASignerRoute: AgentFip6DossiersRejetASignerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
