/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './source/__root'
import { Route as AgentIndexRouteImport } from './source/agent/index'
import { Route as AgentFip3DossiersRejetASignerRouteImport } from './source/agent/fip3/dossiers/rejet-a-signer'
import { Route as AgentFip3DossiersPropositionASignerRouteImport } from './source/agent/fip3/dossiers/proposition-a-signer'
import { Route as AgentFip3DossiersEnAttenteIndemnisationRouteImport } from './source/agent/fip3/dossiers/en-attente-indemnisation'
import { Route as AgentFip3DossiersArreteASignerRouteImport } from './source/agent/fip3/dossiers/arrete-a-signer'
import { Route as AgentFip3DossiersAVerifierRouteImport } from './source/agent/fip3/dossiers/a-verifier'
import { Route as AgentFip3DossiersATransmettreRouteImport } from './source/agent/fip3/dossiers/a-transmettre'
import { Route as AgentFip3DossiersAInstruireRouteImport } from './source/agent/fip3/dossiers/a-instruire'
import { Route as AgentFip3DossiersAAttribuerRouteImport } from './source/agent/fip3/dossiers/a-attribuer'

const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentFip3DossiersRejetASignerRoute =
  AgentFip3DossiersRejetASignerRouteImport.update({
    id: '/agent/fip3/dossiers/rejet-a-signer',
    path: '/agent/fip3/dossiers/rejet-a-signer',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip3DossiersPropositionASignerRoute =
  AgentFip3DossiersPropositionASignerRouteImport.update({
    id: '/agent/fip3/dossiers/proposition-a-signer',
    path: '/agent/fip3/dossiers/proposition-a-signer',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip3DossiersEnAttenteIndemnisationRoute =
  AgentFip3DossiersEnAttenteIndemnisationRouteImport.update({
    id: '/agent/fip3/dossiers/en-attente-indemnisation',
    path: '/agent/fip3/dossiers/en-attente-indemnisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip3DossiersArreteASignerRoute =
  AgentFip3DossiersArreteASignerRouteImport.update({
    id: '/agent/fip3/dossiers/arrete-a-signer',
    path: '/agent/fip3/dossiers/arrete-a-signer',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip3DossiersAVerifierRoute =
  AgentFip3DossiersAVerifierRouteImport.update({
    id: '/agent/fip3/dossiers/a-verifier',
    path: '/agent/fip3/dossiers/a-verifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip3DossiersATransmettreRoute =
  AgentFip3DossiersATransmettreRouteImport.update({
    id: '/agent/fip3/dossiers/a-transmettre',
    path: '/agent/fip3/dossiers/a-transmettre',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip3DossiersAInstruireRoute =
  AgentFip3DossiersAInstruireRouteImport.update({
    id: '/agent/fip3/dossiers/a-instruire',
    path: '/agent/fip3/dossiers/a-instruire',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip3DossiersAAttribuerRoute =
  AgentFip3DossiersAAttribuerRouteImport.update({
    id: '/agent/fip3/dossiers/a-attribuer',
    path: '/agent/fip3/dossiers/a-attribuer',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/agent': typeof AgentIndexRoute
  '/agent/fip3/dossiers/a-attribuer': typeof AgentFip3DossiersAAttribuerRoute
  '/agent/fip3/dossiers/a-instruire': typeof AgentFip3DossiersAInstruireRoute
  '/agent/fip3/dossiers/a-transmettre': typeof AgentFip3DossiersATransmettreRoute
  '/agent/fip3/dossiers/a-verifier': typeof AgentFip3DossiersAVerifierRoute
  '/agent/fip3/dossiers/arrete-a-signer': typeof AgentFip3DossiersArreteASignerRoute
  '/agent/fip3/dossiers/en-attente-indemnisation': typeof AgentFip3DossiersEnAttenteIndemnisationRoute
  '/agent/fip3/dossiers/proposition-a-signer': typeof AgentFip3DossiersPropositionASignerRoute
  '/agent/fip3/dossiers/rejet-a-signer': typeof AgentFip3DossiersRejetASignerRoute
}
export interface FileRoutesByTo {
  '/agent': typeof AgentIndexRoute
  '/agent/fip3/dossiers/a-attribuer': typeof AgentFip3DossiersAAttribuerRoute
  '/agent/fip3/dossiers/a-instruire': typeof AgentFip3DossiersAInstruireRoute
  '/agent/fip3/dossiers/a-transmettre': typeof AgentFip3DossiersATransmettreRoute
  '/agent/fip3/dossiers/a-verifier': typeof AgentFip3DossiersAVerifierRoute
  '/agent/fip3/dossiers/arrete-a-signer': typeof AgentFip3DossiersArreteASignerRoute
  '/agent/fip3/dossiers/en-attente-indemnisation': typeof AgentFip3DossiersEnAttenteIndemnisationRoute
  '/agent/fip3/dossiers/proposition-a-signer': typeof AgentFip3DossiersPropositionASignerRoute
  '/agent/fip3/dossiers/rejet-a-signer': typeof AgentFip3DossiersRejetASignerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/agent/': typeof AgentIndexRoute
  '/agent/fip3/dossiers/a-attribuer': typeof AgentFip3DossiersAAttribuerRoute
  '/agent/fip3/dossiers/a-instruire': typeof AgentFip3DossiersAInstruireRoute
  '/agent/fip3/dossiers/a-transmettre': typeof AgentFip3DossiersATransmettreRoute
  '/agent/fip3/dossiers/a-verifier': typeof AgentFip3DossiersAVerifierRoute
  '/agent/fip3/dossiers/arrete-a-signer': typeof AgentFip3DossiersArreteASignerRoute
  '/agent/fip3/dossiers/en-attente-indemnisation': typeof AgentFip3DossiersEnAttenteIndemnisationRoute
  '/agent/fip3/dossiers/proposition-a-signer': typeof AgentFip3DossiersPropositionASignerRoute
  '/agent/fip3/dossiers/rejet-a-signer': typeof AgentFip3DossiersRejetASignerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agent'
    | '/agent/fip3/dossiers/a-attribuer'
    | '/agent/fip3/dossiers/a-instruire'
    | '/agent/fip3/dossiers/a-transmettre'
    | '/agent/fip3/dossiers/a-verifier'
    | '/agent/fip3/dossiers/arrete-a-signer'
    | '/agent/fip3/dossiers/en-attente-indemnisation'
    | '/agent/fip3/dossiers/proposition-a-signer'
    | '/agent/fip3/dossiers/rejet-a-signer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agent'
    | '/agent/fip3/dossiers/a-attribuer'
    | '/agent/fip3/dossiers/a-instruire'
    | '/agent/fip3/dossiers/a-transmettre'
    | '/agent/fip3/dossiers/a-verifier'
    | '/agent/fip3/dossiers/arrete-a-signer'
    | '/agent/fip3/dossiers/en-attente-indemnisation'
    | '/agent/fip3/dossiers/proposition-a-signer'
    | '/agent/fip3/dossiers/rejet-a-signer'
  id:
    | '__root__'
    | '/agent/'
    | '/agent/fip3/dossiers/a-attribuer'
    | '/agent/fip3/dossiers/a-instruire'
    | '/agent/fip3/dossiers/a-transmettre'
    | '/agent/fip3/dossiers/a-verifier'
    | '/agent/fip3/dossiers/arrete-a-signer'
    | '/agent/fip3/dossiers/en-attente-indemnisation'
    | '/agent/fip3/dossiers/proposition-a-signer'
    | '/agent/fip3/dossiers/rejet-a-signer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AgentIndexRoute: typeof AgentIndexRoute
  AgentFip3DossiersAAttribuerRoute: typeof AgentFip3DossiersAAttribuerRoute
  AgentFip3DossiersAInstruireRoute: typeof AgentFip3DossiersAInstruireRoute
  AgentFip3DossiersATransmettreRoute: typeof AgentFip3DossiersATransmettreRoute
  AgentFip3DossiersAVerifierRoute: typeof AgentFip3DossiersAVerifierRoute
  AgentFip3DossiersArreteASignerRoute: typeof AgentFip3DossiersArreteASignerRoute
  AgentFip3DossiersEnAttenteIndemnisationRoute: typeof AgentFip3DossiersEnAttenteIndemnisationRoute
  AgentFip3DossiersPropositionASignerRoute: typeof AgentFip3DossiersPropositionASignerRoute
  AgentFip3DossiersRejetASignerRoute: typeof AgentFip3DossiersRejetASignerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/rejet-a-signer': {
      id: '/agent/fip3/dossiers/rejet-a-signer'
      path: '/agent/fip3/dossiers/rejet-a-signer'
      fullPath: '/agent/fip3/dossiers/rejet-a-signer'
      preLoaderRoute: typeof AgentFip3DossiersRejetASignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/proposition-a-signer': {
      id: '/agent/fip3/dossiers/proposition-a-signer'
      path: '/agent/fip3/dossiers/proposition-a-signer'
      fullPath: '/agent/fip3/dossiers/proposition-a-signer'
      preLoaderRoute: typeof AgentFip3DossiersPropositionASignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/en-attente-indemnisation': {
      id: '/agent/fip3/dossiers/en-attente-indemnisation'
      path: '/agent/fip3/dossiers/en-attente-indemnisation'
      fullPath: '/agent/fip3/dossiers/en-attente-indemnisation'
      preLoaderRoute: typeof AgentFip3DossiersEnAttenteIndemnisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/arrete-a-signer': {
      id: '/agent/fip3/dossiers/arrete-a-signer'
      path: '/agent/fip3/dossiers/arrete-a-signer'
      fullPath: '/agent/fip3/dossiers/arrete-a-signer'
      preLoaderRoute: typeof AgentFip3DossiersArreteASignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/a-verifier': {
      id: '/agent/fip3/dossiers/a-verifier'
      path: '/agent/fip3/dossiers/a-verifier'
      fullPath: '/agent/fip3/dossiers/a-verifier'
      preLoaderRoute: typeof AgentFip3DossiersAVerifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/a-transmettre': {
      id: '/agent/fip3/dossiers/a-transmettre'
      path: '/agent/fip3/dossiers/a-transmettre'
      fullPath: '/agent/fip3/dossiers/a-transmettre'
      preLoaderRoute: typeof AgentFip3DossiersATransmettreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/a-instruire': {
      id: '/agent/fip3/dossiers/a-instruire'
      path: '/agent/fip3/dossiers/a-instruire'
      fullPath: '/agent/fip3/dossiers/a-instruire'
      preLoaderRoute: typeof AgentFip3DossiersAInstruireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/a-attribuer': {
      id: '/agent/fip3/dossiers/a-attribuer'
      path: '/agent/fip3/dossiers/a-attribuer'
      fullPath: '/agent/fip3/dossiers/a-attribuer'
      preLoaderRoute: typeof AgentFip3DossiersAAttribuerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AgentIndexRoute: AgentIndexRoute,
  AgentFip3DossiersAAttribuerRoute: AgentFip3DossiersAAttribuerRoute,
  AgentFip3DossiersAInstruireRoute: AgentFip3DossiersAInstruireRoute,
  AgentFip3DossiersATransmettreRoute: AgentFip3DossiersATransmettreRoute,
  AgentFip3DossiersAVerifierRoute: AgentFip3DossiersAVerifierRoute,
  AgentFip3DossiersArreteASignerRoute: AgentFip3DossiersArreteASignerRoute,
  AgentFip3DossiersEnAttenteIndemnisationRoute:
    AgentFip3DossiersEnAttenteIndemnisationRoute,
  AgentFip3DossiersPropositionASignerRoute:
    AgentFip3DossiersPropositionASignerRoute,
  AgentFip3DossiersRejetASignerRoute: AgentFip3DossiersRejetASignerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
