/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './source/__root'
import { Route as AgentIndexRouteImport } from './source/agent/index'
import { Route as AgentFip3DossiersEnAttenteIndemnisationRouteImport } from './source/agent/fip3/dossiers/en-attente-indemnisation'
import { Route as AgentFip3DossiersATransmettreRouteImport } from './source/agent/fip3/dossiers/a-transmettre'
import { Route as AgentFip3DossiersAAttribuerRouteImport } from './source/agent/fip3/dossiers/a-attribuer'

const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentFip3DossiersEnAttenteIndemnisationRoute =
  AgentFip3DossiersEnAttenteIndemnisationRouteImport.update({
    id: '/agent/fip3/dossiers/en-attente-indemnisation',
    path: '/agent/fip3/dossiers/en-attente-indemnisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip3DossiersATransmettreRoute =
  AgentFip3DossiersATransmettreRouteImport.update({
    id: '/agent/fip3/dossiers/a-transmettre',
    path: '/agent/fip3/dossiers/a-transmettre',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFip3DossiersAAttribuerRoute =
  AgentFip3DossiersAAttribuerRouteImport.update({
    id: '/agent/fip3/dossiers/a-attribuer',
    path: '/agent/fip3/dossiers/a-attribuer',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/agent': typeof AgentIndexRoute
  '/agent/fip3/dossiers/a-attribuer': typeof AgentFip3DossiersAAttribuerRoute
  '/agent/fip3/dossiers/a-transmettre': typeof AgentFip3DossiersATransmettreRoute
  '/agent/fip3/dossiers/en-attente-indemnisation': typeof AgentFip3DossiersEnAttenteIndemnisationRoute
}
export interface FileRoutesByTo {
  '/agent': typeof AgentIndexRoute
  '/agent/fip3/dossiers/a-attribuer': typeof AgentFip3DossiersAAttribuerRoute
  '/agent/fip3/dossiers/a-transmettre': typeof AgentFip3DossiersATransmettreRoute
  '/agent/fip3/dossiers/en-attente-indemnisation': typeof AgentFip3DossiersEnAttenteIndemnisationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/agent/': typeof AgentIndexRoute
  '/agent/fip3/dossiers/a-attribuer': typeof AgentFip3DossiersAAttribuerRoute
  '/agent/fip3/dossiers/a-transmettre': typeof AgentFip3DossiersATransmettreRoute
  '/agent/fip3/dossiers/en-attente-indemnisation': typeof AgentFip3DossiersEnAttenteIndemnisationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agent'
    | '/agent/fip3/dossiers/a-attribuer'
    | '/agent/fip3/dossiers/a-transmettre'
    | '/agent/fip3/dossiers/en-attente-indemnisation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agent'
    | '/agent/fip3/dossiers/a-attribuer'
    | '/agent/fip3/dossiers/a-transmettre'
    | '/agent/fip3/dossiers/en-attente-indemnisation'
  id:
    | '__root__'
    | '/agent/'
    | '/agent/fip3/dossiers/a-attribuer'
    | '/agent/fip3/dossiers/a-transmettre'
    | '/agent/fip3/dossiers/en-attente-indemnisation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AgentIndexRoute: typeof AgentIndexRoute
  AgentFip3DossiersAAttribuerRoute: typeof AgentFip3DossiersAAttribuerRoute
  AgentFip3DossiersATransmettreRoute: typeof AgentFip3DossiersATransmettreRoute
  AgentFip3DossiersEnAttenteIndemnisationRoute: typeof AgentFip3DossiersEnAttenteIndemnisationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/en-attente-indemnisation': {
      id: '/agent/fip3/dossiers/en-attente-indemnisation'
      path: '/agent/fip3/dossiers/en-attente-indemnisation'
      fullPath: '/agent/fip3/dossiers/en-attente-indemnisation'
      preLoaderRoute: typeof AgentFip3DossiersEnAttenteIndemnisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/a-transmettre': {
      id: '/agent/fip3/dossiers/a-transmettre'
      path: '/agent/fip3/dossiers/a-transmettre'
      fullPath: '/agent/fip3/dossiers/a-transmettre'
      preLoaderRoute: typeof AgentFip3DossiersATransmettreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fip3/dossiers/a-attribuer': {
      id: '/agent/fip3/dossiers/a-attribuer'
      path: '/agent/fip3/dossiers/a-attribuer'
      fullPath: '/agent/fip3/dossiers/a-attribuer'
      preLoaderRoute: typeof AgentFip3DossiersAAttribuerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AgentIndexRoute: AgentIndexRoute,
  AgentFip3DossiersAAttribuerRoute: AgentFip3DossiersAAttribuerRoute,
  AgentFip3DossiersATransmettreRoute: AgentFip3DossiersATransmettreRoute,
  AgentFip3DossiersEnAttenteIndemnisationRoute:
    AgentFip3DossiersEnAttenteIndemnisationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
