api_platform:
    title: API microservices PRECONTENTIEUX
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    show_webby: false
    #docs_formats:
    #    jsonld: ['application/ld+json']
    #    jsonopenapi: ['application/vnd.openapi+json']
    #    html: ['text/html']
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    enable_swagger: false
    enable_swagger_ui: false
    enable_re_doc: false
    enable_entrypoint: false
    enable_docs: false

when@dev:
    api_platform:
        http_cache: ~

when@test:
    api_platform:
        http_cache: ~