framework:
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        pools:
            oidc:
                adapter: cache.adapter.filesystem

when@dev:
    framework:
        cache:
            pools:
                oidc:
                    adapter: cache.adapter.null