when@prod: &prod
    sentry:
        # See https://docs.sentry.io/platforms/php/guides/symfony/configuration/
        dsn: '%env(SENTRY_DSN)%'
        options:
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'
                - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
                - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
            send-default-pii: true

when@develop: *prod
