vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        document:
            uri_prefix: /document
            upload_destination: aws.storage
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 50 }
