vich_uploader:
    db_driver: orm

    mappings:
        document:
            uri_prefix: /document
            upload_destination: '%kernel.project_dir%/public/document'
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 50 }
