include:
  - project: anje/template-ci/symfony
    ref: main
    file:
      - 'package.yml'
      - 'build.yml'
  - project: anje/template-ci/clevercloud
    ref: main
    file:
      - 'deploy.yml'
      - 'destroy.yml'

stages:
  - 🔨build
  - 📦package
  - 🚀deploy
  - 🗑destroy

variables:
  GIT_DEPTH: 0
  APP_NAME: "se-precontentieux-webapp-$CI_COMMIT_REF_SLUG"
  CI_PROJECT_IMAGE: ${APP_NAME}:${CI_COMMIT_SHORT_SHA}_${CI_PIPELINE_IID}
  BRANCH_NAME: ${CI_COMMIT_REF_SLUG}
  APP_ENV: "internet"
  SCW_BUCKET_DEV: se-precontentieux-dev
  

build:
  stage: 🔨build
  image: "registry.anje-justice.fr/anje/anj-php:8.2-apache-pgsql-apcu"
  artifacts:
    paths:
      - vendor/
      - public/
      - .env*
      - composer.lock
    expire_in: 05 min
  cache:
    paths:
      - vendor/
      - public/

package:
  stage: 📦package
  needs:
    - job : build
      artifacts: true
  image:
    name: "gcr.io/kaniko-project/executor:v1.9.0-debug"
    entrypoint: [ '' ]
  script:
    - echo "Package to Docker image Spring boot application"
    - mkdir -p /kaniko/.docker
    - echo "$REGISTRY_AUTH" | base64 -d > /kaniko/.docker/config.json
    - ls -lsa /kaniko/.docker/config.json
    # Kaniko documentation https://github.com/GoogleContainerTools/kaniko?tab=readme-ov-file#additional-flags
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/.docker/apache/Dockerfile"
      --build-arg APP_ENV=prod
      --target base
      --destination "${REGISTRY_URL}/${CI_PROJECT_IMAGE}"

deploy-develop:
  stage: 🚀deploy
  needs:
    - job: package
  extends: .template:clevercloud:deploy
  variables:
    APP_FQDN: "dev.precontentieux.app.cc.anje-justice.fr"
    CC_DOCKER_EXPOSED_HTTP_PORT: 8080
    CC_FORCE_HTTPS: 1
    CLEVER_PGNAME: "postgresql_9c6a16f6-acc0-4152-8bc4-29f21ef185d1"
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: "https://dev.precontentieux.app.cc.anje-justice.fr"
  only:
    - develop

deploy-recette:
  stage: 🚀deploy
  needs:
    - job: package
  extends: .template:clevercloud:deploy
  variables:
    APP_FQDN: "recette.precontentieux.app.cc.anje-justice.fr"
    CC_DOCKER_EXPOSED_HTTP_PORT: 8080
    CC_FORCE_HTTPS: 1
    CLEVER_PGNAME: "postgresql_9c6a16f6-acc0-4152-8bc4-29f21ef185d1"
  environment:
    name: recette/$CI_COMMIT_REF_SLUG
    url: "https://recette.precontentieux.app.cc.anje-justice.fr"
  only:
    - recette


deploy-production:
  stage: 🚀deploy
  needs:
    - job: package
  extends: .template:clevercloud:deploy
  variables:
    APP_FQDN: "precontentieux.app.cc.anje-justice.fr"
    CC_DOCKER_EXPOSED_HTTP_PORT: 8080
    CC_FORCE_HTTPS: 1
    CLEVER_PGNAME: "postgresql_9c6a16f6-acc0-4152-8bc4-29f21ef185d1"
    S3_ENDPOINT: "https://s3.fr-par.scw.cloud"
    S3_BUCKET: "se-precontentieux-prod"
    S3_ACCESS_KEY: $S3_ACCESS_KEY_SECRET
    S3_SECRET_KEY: $S3_SECRET_KEY_SECRET
  environment:
    name: prod/$CI_COMMIT_REF_SLUG
    url: "https://precontentieux.app.cc.anje-justice.fr"
  when: manual
  only:
    - master

destroy-app-clevercloud:
  stage: 🗑destroy
  extends: .template:clevercloud:destroy