

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop"
      variables:
        CC_APP_ID: ${CC_APP_DEV_ID}
    - when: always


stages:
  - "🔨 build"
  - "🚀 deploy"


variables:
  GIT_DEPTH: 0
  APP_NAME: "se-precontentieux-webapp-$CI_COMMIT_REF_SLUG"
  CI_PROJECT_IMAGE: ${APP_NAME}:${CI_COMMIT_SHORT_SHA}_${CI_PIPELINE_IID}
  BRANCH_NAME: ${CI_COMMIT_REF_SLUG}
  APP_ENV: "internet"
  SCW_BUCKET_DEV: se-precontentieux-dev
  

build:
  stage: "🔨 build"
  variables:
    APP_ENV: test
    DATABASE_URL: pgsql://precontest:precontest@postgres:5432/precontest?serverVersion=15
    POSTGRES_DB: precontest
    POSTGRES_PASSWORD: precontest
    POSTGRES_USER: precontest
  services:
    - postgres:15-alpine
  image:
    name: composer:lts
  script:
    - echo "Building"
    - composer install
    - bin/phpunit
  artifacts:
    paths:
      - vendor/
      - public/
      - .env*
      - composer.lock
    expire_in: 05 min
  cache:
    paths:
      - vendor/
      - public/

deploy:
  stage: "🚀 deploy"
  image:
    name: clevercloud/clever-tools:latest
  needs:
    - job : build
      artifacts: true

  script:
    - echo "Package"
    - echo APP ID ${CC_APP_ID}
    - clever link "${CC_APP_ID}"
    - clever deploy
  only:
    - develop
