stages:
  - "🔨 build"
  - "🚀 deploy"

build:
  stage: "🔨 build"
  variables:
    APP_ENV: test
    APP_SECRET: bafc23a0315b735289c499a886798934
    DATABASE_URL: pgsql://precontentieux:precontentieux@postgres:5432/precontest?serverVersion=15
    COMPOSER_ALLOW_SUPERUSER: 1
    POSTGRES_DB: precontest
    POSTGRES_PASSWORD: precontentieux
    POSTGRES_USER: precontentieux
    BASE_URL: precontentieux.test
    MAILER_FROM: ne-pas-repondre@precontentieux.test
    MAILER_DSN: smtp://mailpit:1025
    CORS_ALLOW_ORIGIN: "*"
    EMAIL_FROM: ne-pas-repondre@precontentieux.anje-justice.test
    EMAIL_FROM_LABEL: "Précontentieux (test)"
    SYMFONY_DEPRECATIONS_HELPER: disabled
    PANTHER_ERROR_SCREENSHOT_DIR: public/screenshots
    PANTHER_ERROR_SCREENSHOT_ATTACH: true
    PANTHER_FIREFOX_ARGUMENTS: "-width=1200 -height=2000"
  services:
    - name: postgres:15-alpine
      alias: postgres
    - name: axllent/mailpit
      alias: mailpit
  image:
    name: pierrelemee/precontentieux-full:latest
  script:
    - echo "Building"
    - composer install --no-interaction --optimize-autoloader
    - bin/console cache:clear
    - bin/console doctrine:migrations:migrate --no-interaction --all-or-nothing
    - yarn install --no-progress --non-interactive
    - yarn build
    # Run unit tests
    - vendor/bin/bdi detect drivers
    - bin/phpunit --log-junit test-result.xml
  artifacts:
    when: always
    paths:
      - test-result.xml
      - public/screenshots/**
    reports:
      junit: test-result.xml
  cache:
    paths:
      - vendor/

deploy-develop:
  stage: "🚀 deploy"
  image:
    name: clevercloud/clever-tools:latest
  script:
    - echo "Deploying"
    - clever link $CC_APP_DEV_ID
    - clever deploy --alias precontentieux-dev --force
  only:
    - develop

deploy-prod:
  stage: "🚀 deploy"
  image:
    name: clevercloud/clever-tools:latest
  script:
    - echo "Deploying"
    - clever link $CC_APP_PROD_ID
    - clever deploy --alias precontentieux-prod --force
  only:
    - prod
