include:
  - project: anje/template-ci/symfony
    ref: main
    file:
      - 'package.yml'
      - 'build.yml'
  - project: anje/template-ci/clevercloud
    ref: main
    file:
      - 'deploy.yml'
      - 'destroy.yml'

stages:
  - 🔨build
  - 📦package
  - 🚀deploy
  - 🗑destroy

variables:
  GIT_DEPTH: 0
  APP_NAME: "se-precontentieux-webapp-$CI_COMMIT_REF_SLUG"
  CI_PROJECT_IMAGE: ${APP_NAME}:${CI_COMMIT_SHORT_SHA}_${CI_PIPELINE_IID}
  BRANCH_NAME: ${CI_COMMIT_REF_SLUG}
  APP_ENV: "internet"
  APP_SECRET: bafc23a0315b735289c499a886798934
  BASE_URL: https://dev.precontentieux.app.cc.anje-justice.fr
  CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
  DATABASE_PASSWORD: ${PSQL_PASSWORD_DEV}
  DATABASE_NAME: ${PSQL_DB_DEV}
  DATABASE_HOST: ${PSQL_HOST_DEV}
  DATABASE_USER: ${PSQL_USERNAME_DEV}
  DATABASE_PORT: ${PSQL_PORT_DEV}
  DATABASE_TYPE: postgres
  DATABASE_DRIVER: pdo_pgsql
  EMAIL_FROM: nepasrepondre@justice.gouv.fr
  EMAIL_FROM_LABEL: Precontentieux
  MAILER_FROM: nepasrepondre@justice.gouv.fr
  VERSION_LABEL: '0.0.1'
  SCW_HOST: 'https://s3.fr-par.scw.cloud'
  SCW_ACCESS_KEY: $S3_ACCESS_KEY_SECRET
  SCW_REGION: fr-par
  SCW_BUCKET: se-precontentieux-dev
  SCW_SECRET_KEY: $S3_SECRET_KEY_SECRET
  SCW_DEFAULT_ORGANIZATION_ID: 2e8f8f84-02bf-4b8f-8cec-f99918fbd746
  SCW_DEFAULT_PROJECT_ID: 2e8f8f84-02bf-4b8f-8cec-f99918fbd746
  # configuration dédiée à la section "mailer"
  MAILER_DSN: 'smtp://null:null@null:25'

build:
  stage: 🔨build
  image: "registry.anje-justice.fr/anje/anj-php:8.2-apache-pgsql-apcu"
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /master/
      variables:
        DATABASE_PASSWORD: ${PSQL_PASSWORD}
        DATABASE_NAME: ${PSQL_DB}
        DATABASE_HOST: ${PSQL_HOST}
        DATABASE_USER: ${PSQL_USERNAME}
        DATABASE_PORT: ${PSQL_PORT}
        BASE_URL: https://precontentieux.app.cc.anje-justice.fr
  before_script:
    - apt-get update
    - apt-get install -y zip unzip
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&\
    - apt-get install -y nodejs
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - php -r "unlink('composer-setup.php');"
    - echo "host db ${DATABASE_HOST}"
  script:
    #- echo "Set .env.${APP_ENV}"
    #- cp .env.$APP_ENV .env
    #- sed -i "s|__PSQL_HOST__|${PSQL_HOST}|g" .env.$APP_ENV
    #- sed -i "s|__PSQL_PORT__|${PSQL_PORT}|g" .env.$APP_ENV
    #- sed -i "s|__PSQL_USERNAME__|${PSQL_USERNAME}|g" .env.$APP_ENV
    #- sed -i "s|__PSQL_PASSWORD__|${PSQL_PASSWORD}|g" .env.$APP_ENV
    #- sed -i "s|__PSQL_DB__|${PSQL_DB}|g" .env.$APP_ENV
    #- sed -i "s|__SMTP_HOST__|${SMTP_HOST}|g" .env.$APP_ENV
    #- sed -i "s|__SMTP_PORT__|${SMTP_PORT}|g" .env.$APP_ENV
    #- sed -i "s|__SMTP_USERNAME__|${SMTP_USERNAME}|g" .env.$APP_ENV
    #- sed -i "s|__SMTP_PASSWORD__|${SMTP_PASSWORD}|g" .env.$APP_ENV
    - echo "Install dependencies Symfony application with composer"
    - composer install --optimize-autoloader --apcu-autoloader
    - echo "Update database"
    - php bin/console d:s:u --force
    - echo "Install Npm & Assets"
    - npm install
    - npm run build
    - php bin/console a:i
    - php bin/console a:a:charger
    - apt-get remove --purge nodejs && apt-get autoremove
    #- COMPOSER_ALLOW_SUPERUSER=1 composer dump-env $APP_ENV
    - COMPOSER_ALLOW_SUPERUSER=1 composer dump-env $APP_ENV
  artifacts:
    paths:
      - vendor/
      - public/
      - .env*
      - composer.lock
    expire_in: 05 min
  cache:
    paths:
      - vendor/
      - public/

package:
  stage: 📦package
  needs:
    - job : build
      artifacts: true
  image:
    name: "gcr.io/kaniko-project/executor:v1.9.0-debug"
    entrypoint: [ '' ]
  script:
    - echo "Package to Docker image Spring boot application"
    - mkdir -p /kaniko/.docker
    - echo "$REGISTRY_AUTH" | base64 -d > /kaniko/.docker/config.json
    - ls -lsa /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/.docker/Dockerfile"
      --destination "${REGISTRY_URL}/${CI_PROJECT_IMAGE}"

deploy-develop:
  stage: 🚀deploy
  needs:
    - job: package
  extends: .template:clevercloud:deploy
  variables:
    APP_FQDN: "dev.precontentieux.app.cc.anje-justice.fr"
    CC_DOCKER_EXPOSED_HTTP_PORT: 8080
    CC_FORCE_HTTPS: 1
    CLEVER_PGNAME: "postgresql_9c6a16f6-acc0-4152-8bc4-29f21ef185d1"
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: "https://dev.precontentieux.app.cc.anje-justice.fr"
  only:
    - develop
  script:
    - echo "host db ${DATABASE_HOST}"

deploy-recette:
  stage: 🚀deploy
  needs:
    - job: package
  extends: .template:clevercloud:deploy
  variables:
    APP_FQDN: "recette.precontentieux.app.cc.anje-justice.fr"
    CC_DOCKER_EXPOSED_HTTP_PORT: 8080
    CC_FORCE_HTTPS: 1
    CLEVER_PGNAME: "postgresql_9c6a16f6-acc0-4152-8bc4-29f21ef185d1"
  environment:
    name: recette/$CI_COMMIT_REF_SLUG
    url: "https://recette.precontentieux.app.cc.anje-justice.fr"
  only:
    - recette


deploy-production:
  stage: 🚀deploy
  needs:
    - job: package
  extends: .template:clevercloud:deploy
  variables:
    APP_FQDN: "precontentieux.app.cc.anje-justice.fr"
    CC_DOCKER_EXPOSED_HTTP_PORT: 8080
    CC_FORCE_HTTPS: 1
    CLEVER_PGNAME: "postgresql_9c6a16f6-acc0-4152-8bc4-29f21ef185d1"
    S3_ENDPOINT: "https://s3.fr-par.scw.cloud"
    S3_BUCKET: "se-precontentieux-prod"
    S3_ACCESS_KEY: $S3_ACCESS_KEY_SECRET
    S3_SECRET_KEY: $S3_SECRET_KEY_SECRET
  environment:
    name: prod/$CI_COMMIT_REF_SLUG
    url: "https://precontentieux.app.cc.anje-justice.fr"
  when: manual
  only:
    - master

destroy-app-clevercloud:
  stage: 🗑destroy
  extends: .template:clevercloud:destroy
