services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-precondev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-precontentieux}
      POSTGRES_USER: ${POSTGRES_USER:-precontentieux}
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data:rw
      # To run init scripts, wipe the data dir (`rm -Rf .docker/postgres/data/*`) first
      - ./.docker/postgres/scripts/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  nginx:
    hostname: nginx
    stdin_open: true
    tty: true
    build:
      dockerfile: .docker/nginx/Dockerfile
      context: .
    volumes:
      # Ce partage, via un volume, est requis afin que Nginx puisse servir les fichiers statiques seul
      - ./public:/app/public
    ports:
      - "80:80"
      - "443:443"

  # Mailpit: email SMTP + web UI to see trapped emails
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  # The Symfony app
  symfony:
    platform: linux/amd64
    hostname: symfony
    stdin_open: true
    tty: true
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
      args:
        - APP_ENV=${APP_ENV:-dev}
        - APP_DEBUG=${APP_DEBUG:-1}
        - DATABASE_URL=pgsql://precontentieux:precontentieux@postgres:5432/precondev?serverVersion=15
    environment:
      - APP_ENV=${APP_ENV:-dev}
    depends_on:
      - postgres
      - mailpit
    volumes:
      # Ce partage, via un volume, est requis afin que Symfony puisse lire les manifestes produits par `encore`
      - .:/app
    ports:
      - "9000:9000"

  # Encore dev server (frontend assets)
  encore:
    image: node:18
    hostname: encore
    command: bash -c 'yarn install && yarn dev-server'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8081:8081"
