services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-precondev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-precondev}
      POSTGRES_USER: ${POSTGRES_USER:-precondev}
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data:rw
      # To run init scripts, wipe the data dir (`rm -Rf .docker/postgres/data/*`) first
      - ./.docker/postgres/scripts/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  # Mailpit: email SMTP + web UI to see trapped emails
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  # The Symfony app
  symfony: &app
    platform: linux/amd64
    hostname: symfony
    stdin_open: true
    tty: true
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - APP_ENV=dev
        - DATABASE_URL=pgsql://precondev:precondev@postgres:5432/precondev?serverVersion=15
    environment:
      - APP_ENV=dev
      - DATABASE_URL=pgsql://precondev:precondev@postgres:5432/precondev?serverVersion=15
    depends_on:
      - postgres
      - mailpit
    volumes:
      - ./public:/var/www/html/public
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html
          ignore:
            - vendor/
            - public/build/
            - assets/
        - action: rebuild
          path: composer.lock

  # Encore & webpack dev-server for HMR in local development
  encore:
    <<: *app
    hostname: encore
    command: yarn dev-server --port 8081
    volumes:
      - ./public:/var/www/html/public
    develop:
      watch:
        - action: sync
          path: assets
          target: /var/www/html/assets
          ignore:
            - node_modules/
        - action: rebuild
          path: yarn.lock
    ports:
      - "8081:8081"
