services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

  app:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - APP_ENV=dev
    environment:
      APP_ENV: dev
    depends_on:
      - mailer
      - database
    ports:
      - "8080:80"
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html
          ignore:
            - vendor/
        - action: rebuild
          path: composer.lock

