services:
###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-precondev}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-precondev}
      POSTGRES_USER: ${POSTGRES_USER:-precondev}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
    ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  symfony:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - APP_ENV=dev
    environment:
      APP_ENV: dev
    depends_on:
      - postgres
      - mailpit
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html
          ignore:
            - vendor/
        - action: rebuild
          path: composer.lock

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
