services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-precondev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-precontentieux}
      POSTGRES_USER: ${POSTGRES_USER:-precontentieux}
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data:rw
      # To run init scripts, wipe the data dir (`rm -Rf .docker/postgres/data/*`) first
      - ./.docker/postgres/scripts/:/docker-entrypoint-initdb.d
      # Accès aux fichiers pour les requêtes nécessitant `pg_stat_file`
      - .docker/php/fichiers:/app/fichiers
    networks:
      mijnet:
        aliases:
          - postgres
    ports:
      - "5432:5432"

  nginx:
    hostname: nginx
    stdin_open: true
    tty: true
    build:
      dockerfile: .docker/nginx/Dockerfile
      context: .
    networks:
      mijnet:
        aliases:
          - mon-indemnisation.justice.gouv.dev
          - mon-indemnisation.justice.gouv.test
          - proconnect.gouv.test
          - franceconnect.gouv.test
    ports:
      - "80:80"
      - "443:443"

  # Mailpit: email SMTP + web UI to see trapped emails
  mailpit:
    image: axllent/mailpit
    networks:
      mijnet:
        aliases:
          - mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  # The Symfony app
  symfony: &sf
    hostname: symfony
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: .docker/php/dev.dockerfile
    command: |
      bash -c "composer install --no-interaction --optimize-autoloader && \
      bin/console doctrine:migration:migrate --no-interaction --all-or-nothing && \
      cd /app/public && \
      frankenphp php-server -a ./index.php"
    environment:
      - APP_ENV=dev
      - SYMFONY_DEPRECATIONS_HELPER=disabled
      - MAILPIT_URL=http://mailpit:8025
      - SERVER_NAME=:80
      - HTTPS=true;
      - REQUEST_SCHEME=https
      - FIREFOX_PATH=/usr/bin/firefox
    restart: always
    depends_on:
      - postgres
      - mailpit
      - vite
      - franceconnect
      - proconnect
    volumes:
      # Ce partage, via un volume, est requis afin que Symfony puisse lire les manifestes produits par `encore`
      - ./backend:/app
      - ./frontend/public/preview:/app/public/preview
      - .docker/php/fichiers:/app/fichiers
      - /app/vendor
      - /app/var
      - /app/node_modules
      #- ./.docker/nginx/ssl:/usr/local/share/ca-certificates
    networks:
      - mijnet
    ports:
      - "8001:80"

  test:
    hostname: test
    build:
      context: .
      dockerfile: .docker/php/prod.dockerfile
      args:
        - APP_ENV=test
        - APP_DEBUG=false
        - APP_SECRET=bafc23a0315b735289c499a886798934
        - DATABASE_URL=pgsql://precontentieux:precontentieux@postgres:5432/precontest?serverVersion=15&charset=utf8
        - BASE_URL=https://mon-indemnisation.justice.gouv.test
        - COMPOSER_OPTS=
    networks:
      mijnet:
    environment:
      - APP_ENV=test
      - SYMFONY_DEPRECATIONS_HELPER=disabled
      - MAILPIT_URL=http://mailpit:8025
      #- MIJ_DOMAINE_PRIMAIRE=mon-indemnisation.justice.gouv.dev
      - SERVER_NAME=:80
      - HTTPS=true;
      - REQUEST_SCHEME=https
    volumes:
      - .docker/php/fichiers:/app/fichiers
      - ./backend/.env.test:/app/.env.test
    ports:
      - "8002:80"

  # Vite dev server
  vite:
    hostname: vite
    stdin_open: true
    tty: true
    # En attendant un accès à Harbor
    build:
      context: .
      dockerfile: .docker/vite/Dockerfile
    networks:
      mijnet:
        aliases:
          - vite
    command: bash -c 'yarn install && yarn dev'
    working_dir: /app
    volumes:
      - ./frontend:/app
      # Dossier à ne pas partager entre guest et host
      - /app/node_modules
    ports:
      - "5173:5173"

  franceconnect:
    image: pierrelemee/mock-oidc-server
    hostname: franceconnect
    networks:
      mijnet:
        aliases:
          - franceconnect
    ports:
      - '9997:9997'
    environment:
      PORT: 9997
      HOST: '0.0.0.0'
      # Liste exhaustive des exemples : https://github.com/france-connect/sources/blob/main/docker/volumes/fcp-low/mocks/idp/databases/citizen/base.csv
      USERS: "/app/data/usagers.json"
    working_dir: /app
    volumes:
      - ./.docker/franceconnect:/app/data/

  proconnect:
    image: pierrelemee/mock-oidc-server
    hostname: proconnect
    networks:
      mijnet:
        aliases:
          - proconnect
    ports:
      - '9998:9998'
    environment:
      PORT: 9998
      HOST: '0.0.0.0'
      USERS: "/app/data/users.json"
    working_dir: /app
    volumes:
      - ./.docker/proconnect:/app/data/

  playwright:
    profiles:
      - playwright
    build:
      dockerfile: .docker/playwright/Dockerfile
      context: .
    hostname: playwright
    networks:
      mijnet:
        aliases:
          - playwright
    command: npx playwright test --ui-port=8080 --ui-host=0.0.0.0 --project firefox
    volumes:
      - ./end2end/tests:/app/tests
    ports:
      - "8080:8080"
      - "3000:3000"

networks:
  mijnet:
