services:
###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-precondev}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-precondev}
      POSTGRES_USER: ${POSTGRES_USER:-precondev}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
    ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  symfony: &app
    hostname: symfony
    stdin_open: true
    tty: true
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - APP_ENV=dev
    environment:
      APP_ENV: dev
    depends_on:
      - postgres
      - mailpit
    volumes:
      - ./public:/var/www/html/public
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html
          ignore:
            - vendor/
            - public/build/
            - assets/
        - action: rebuild
          path: composer.lock

  encore:
    <<: *app
    hostname: encore
    command: yarn dev-server --port 8081
    volumes:
      - ./public:/var/www/html/public
    develop:
      watch:
        - action: sync
          path: assets
          target: /var/www/html/assets
          ignore:
            - node_modules/
        - action: rebuild
          path: yarn.lock
    ports:
      - "8081:8081"

volumes:
  database_data: