/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as VisiteurIndexRouteImport } from './../routes/visiteur/index'
import { Route as VisiteurTestEligibiliteRouteImport } from './../routes/visiteur/test-eligibilite'
import { Route as VisiteurResultatRouteImport } from './../routes/visiteur/resultat'
import { Route as VisiteurEtapesEligibiliteRouteImport } from './../routes/visiteur/etapes-eligibilite'

const VisiteurIndexRoute = VisiteurIndexRouteImport.update({
  id: '/visiteur/',
  path: '/visiteur/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisiteurTestEligibiliteRoute = VisiteurTestEligibiliteRouteImport.update({
  id: '/visiteur/test-eligibilite',
  path: '/visiteur/test-eligibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const VisiteurResultatRoute = VisiteurResultatRouteImport.update({
  id: '/visiteur/resultat',
  path: '/visiteur/resultat',
  getParentRoute: () => rootRouteImport,
} as any)
const VisiteurEtapesEligibiliteRoute =
  VisiteurEtapesEligibiliteRouteImport.update({
    id: '/visiteur/etapes-eligibilite',
    path: '/visiteur/etapes-eligibilite',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/visiteur/etapes-eligibilite': typeof VisiteurEtapesEligibiliteRoute
  '/visiteur/resultat': typeof VisiteurResultatRoute
  '/visiteur/test-eligibilite': typeof VisiteurTestEligibiliteRoute
  '/visiteur': typeof VisiteurIndexRoute
}
export interface FileRoutesByTo {
  '/visiteur/etapes-eligibilite': typeof VisiteurEtapesEligibiliteRoute
  '/visiteur/resultat': typeof VisiteurResultatRoute
  '/visiteur/test-eligibilite': typeof VisiteurTestEligibiliteRoute
  '/visiteur': typeof VisiteurIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/visiteur/etapes-eligibilite': typeof VisiteurEtapesEligibiliteRoute
  '/visiteur/resultat': typeof VisiteurResultatRoute
  '/visiteur/test-eligibilite': typeof VisiteurTestEligibiliteRoute
  '/visiteur/': typeof VisiteurIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/visiteur/etapes-eligibilite'
    | '/visiteur/resultat'
    | '/visiteur/test-eligibilite'
    | '/visiteur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/visiteur/etapes-eligibilite'
    | '/visiteur/resultat'
    | '/visiteur/test-eligibilite'
    | '/visiteur'
  id:
    | '__root__'
    | '/visiteur/etapes-eligibilite'
    | '/visiteur/resultat'
    | '/visiteur/test-eligibilite'
    | '/visiteur/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VisiteurEtapesEligibiliteRoute: typeof VisiteurEtapesEligibiliteRoute
  VisiteurResultatRoute: typeof VisiteurResultatRoute
  VisiteurTestEligibiliteRoute: typeof VisiteurTestEligibiliteRoute
  VisiteurIndexRoute: typeof VisiteurIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visiteur/': {
      id: '/visiteur/'
      path: '/visiteur'
      fullPath: '/visiteur'
      preLoaderRoute: typeof VisiteurIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visiteur/test-eligibilite': {
      id: '/visiteur/test-eligibilite'
      path: '/visiteur/test-eligibilite'
      fullPath: '/visiteur/test-eligibilite'
      preLoaderRoute: typeof VisiteurTestEligibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visiteur/resultat': {
      id: '/visiteur/resultat'
      path: '/visiteur/resultat'
      fullPath: '/visiteur/resultat'
      preLoaderRoute: typeof VisiteurResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visiteur/etapes-eligibilite': {
      id: '/visiteur/etapes-eligibilite'
      path: '/visiteur/etapes-eligibilite'
      fullPath: '/visiteur/etapes-eligibilite'
      preLoaderRoute: typeof VisiteurEtapesEligibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  VisiteurEtapesEligibiliteRoute: VisiteurEtapesEligibiliteRoute,
  VisiteurResultatRoute: VisiteurResultatRoute,
  VisiteurTestEligibiliteRoute: VisiteurTestEligibiliteRoute,
  VisiteurIndexRoute: VisiteurIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
