/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as DeniDeJusticeTesterMonEligibiliteIndexRouteImport } from './../routes/deni-de-justice/tester-mon-eligibilite/index'
import { Route as DeniDeJusticeTesterMonEligibiliteTestEligibiliteRouteImport } from './../routes/deni-de-justice/tester-mon-eligibilite/test-eligibilite'
import { Route as DeniDeJusticeTesterMonEligibiliteResultatRouteImport } from './../routes/deni-de-justice/tester-mon-eligibilite/resultat'
import { Route as DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRouteImport } from './../routes/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite'

const DeniDeJusticeTesterMonEligibiliteIndexRoute =
  DeniDeJusticeTesterMonEligibiliteIndexRouteImport.update({
    id: '/deni-de-justice/tester-mon-eligibilite/',
    path: '/deni-de-justice/tester-mon-eligibilite/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeniDeJusticeTesterMonEligibiliteTestEligibiliteRoute =
  DeniDeJusticeTesterMonEligibiliteTestEligibiliteRouteImport.update({
    id: '/deni-de-justice/tester-mon-eligibilite/test-eligibilite',
    path: '/deni-de-justice/tester-mon-eligibilite/test-eligibilite',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeniDeJusticeTesterMonEligibiliteResultatRoute =
  DeniDeJusticeTesterMonEligibiliteResultatRouteImport.update({
    id: '/deni-de-justice/tester-mon-eligibilite/resultat',
    path: '/deni-de-justice/tester-mon-eligibilite/resultat',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRoute =
  DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRouteImport.update({
    id: '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite',
    path: '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite': typeof DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRoute
  '/deni-de-justice/tester-mon-eligibilite/resultat': typeof DeniDeJusticeTesterMonEligibiliteResultatRoute
  '/deni-de-justice/tester-mon-eligibilite/test-eligibilite': typeof DeniDeJusticeTesterMonEligibiliteTestEligibiliteRoute
  '/deni-de-justice/tester-mon-eligibilite/': typeof DeniDeJusticeTesterMonEligibiliteIndexRoute
}
export interface FileRoutesByTo {
  '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite': typeof DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRoute
  '/deni-de-justice/tester-mon-eligibilite/resultat': typeof DeniDeJusticeTesterMonEligibiliteResultatRoute
  '/deni-de-justice/tester-mon-eligibilite/test-eligibilite': typeof DeniDeJusticeTesterMonEligibiliteTestEligibiliteRoute
  '/deni-de-justice/tester-mon-eligibilite': typeof DeniDeJusticeTesterMonEligibiliteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite': typeof DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRoute
  '/deni-de-justice/tester-mon-eligibilite/resultat': typeof DeniDeJusticeTesterMonEligibiliteResultatRoute
  '/deni-de-justice/tester-mon-eligibilite/test-eligibilite': typeof DeniDeJusticeTesterMonEligibiliteTestEligibiliteRoute
  '/deni-de-justice/tester-mon-eligibilite/': typeof DeniDeJusticeTesterMonEligibiliteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite'
    | '/deni-de-justice/tester-mon-eligibilite/resultat'
    | '/deni-de-justice/tester-mon-eligibilite/test-eligibilite'
    | '/deni-de-justice/tester-mon-eligibilite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite'
    | '/deni-de-justice/tester-mon-eligibilite/resultat'
    | '/deni-de-justice/tester-mon-eligibilite/test-eligibilite'
    | '/deni-de-justice/tester-mon-eligibilite'
  id:
    | '__root__'
    | '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite'
    | '/deni-de-justice/tester-mon-eligibilite/resultat'
    | '/deni-de-justice/tester-mon-eligibilite/test-eligibilite'
    | '/deni-de-justice/tester-mon-eligibilite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRoute: typeof DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRoute
  DeniDeJusticeTesterMonEligibiliteResultatRoute: typeof DeniDeJusticeTesterMonEligibiliteResultatRoute
  DeniDeJusticeTesterMonEligibiliteTestEligibiliteRoute: typeof DeniDeJusticeTesterMonEligibiliteTestEligibiliteRoute
  DeniDeJusticeTesterMonEligibiliteIndexRoute: typeof DeniDeJusticeTesterMonEligibiliteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/deni-de-justice/tester-mon-eligibilite/': {
      id: '/deni-de-justice/tester-mon-eligibilite/'
      path: '/deni-de-justice/tester-mon-eligibilite'
      fullPath: '/deni-de-justice/tester-mon-eligibilite/'
      preLoaderRoute: typeof DeniDeJusticeTesterMonEligibiliteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deni-de-justice/tester-mon-eligibilite/test-eligibilite': {
      id: '/deni-de-justice/tester-mon-eligibilite/test-eligibilite'
      path: '/deni-de-justice/tester-mon-eligibilite/test-eligibilite'
      fullPath: '/deni-de-justice/tester-mon-eligibilite/test-eligibilite'
      preLoaderRoute: typeof DeniDeJusticeTesterMonEligibiliteTestEligibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deni-de-justice/tester-mon-eligibilite/resultat': {
      id: '/deni-de-justice/tester-mon-eligibilite/resultat'
      path: '/deni-de-justice/tester-mon-eligibilite/resultat'
      fullPath: '/deni-de-justice/tester-mon-eligibilite/resultat'
      preLoaderRoute: typeof DeniDeJusticeTesterMonEligibiliteResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite': {
      id: '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite'
      path: '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite'
      fullPath: '/deni-de-justice/tester-mon-eligibilite/etapes-eligibilite'
      preLoaderRoute: typeof DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRoute:
    DeniDeJusticeTesterMonEligibiliteEtapesEligibiliteRoute,
  DeniDeJusticeTesterMonEligibiliteResultatRoute:
    DeniDeJusticeTesterMonEligibiliteResultatRoute,
  DeniDeJusticeTesterMonEligibiliteTestEligibiliteRoute:
    DeniDeJusticeTesterMonEligibiliteTestEligibiliteRoute,
  DeniDeJusticeTesterMonEligibiliteIndexRoute:
    DeniDeJusticeTesterMonEligibiliteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
