/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as DysfonctionnementTesterMonEligibiliteIndexRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/index'
import { Route as DysfonctionnementTesterMonEligibiliteTestEligibiliteRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
import { Route as DysfonctionnementTesterMonEligibiliteResultatRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/resultat'
import { Route as DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite'
import { Route as DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite/$etape'

const DysfonctionnementTesterMonEligibiliteIndexRoute =
  DysfonctionnementTesterMonEligibiliteIndexRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/',
    path: '/dysfonctionnement/tester-mon-eligibilite/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute =
  DysfonctionnementTesterMonEligibiliteTestEligibiliteRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite',
    path: '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibiliteResultatRoute =
  DysfonctionnementTesterMonEligibiliteResultatRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/resultat',
    path: '/dysfonctionnement/tester-mon-eligibilite/resultat',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRoute =
  DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite',
    path: '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRoute =
  DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRouteImport.update(
    {
      id: '/$etape',
      path: '/$etape',
      getParentRoute: () =>
        DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite': typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteWithChildren
  '/dysfonctionnement/tester-mon-eligibilite/resultat': typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite': typeof DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute
  '/dysfonctionnement/tester-mon-eligibilite': typeof DysfonctionnementTesterMonEligibiliteIndexRoute
  '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite/$etape': typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRoute
}
export interface FileRoutesByTo {
  '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite': typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteWithChildren
  '/dysfonctionnement/tester-mon-eligibilite/resultat': typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite': typeof DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute
  '/dysfonctionnement/tester-mon-eligibilite': typeof DysfonctionnementTesterMonEligibiliteIndexRoute
  '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite/$etape': typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite': typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteWithChildren
  '/dysfonctionnement/tester-mon-eligibilite/resultat': typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite': typeof DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute
  '/dysfonctionnement/tester-mon-eligibilite/': typeof DysfonctionnementTesterMonEligibiliteIndexRoute
  '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite/$etape': typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite/resultat'
    | '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite/$etape'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite/resultat'
    | '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite/$etape'
  id:
    | '__root__'
    | '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite/resultat'
    | '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite/'
    | '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite/$etape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRoute: typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteWithChildren
  DysfonctionnementTesterMonEligibiliteResultatRoute: typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute: typeof DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute
  DysfonctionnementTesterMonEligibiliteIndexRoute: typeof DysfonctionnementTesterMonEligibiliteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dysfonctionnement/tester-mon-eligibilite/': {
      id: '/dysfonctionnement/tester-mon-eligibilite/'
      path: '/dysfonctionnement/tester-mon-eligibilite'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibiliteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite': {
      id: '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
      path: '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibiliteTestEligibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/resultat': {
      id: '/dysfonctionnement/tester-mon-eligibilite/resultat'
      path: '/dysfonctionnement/tester-mon-eligibilite/resultat'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/resultat'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibiliteResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite': {
      id: '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite'
      path: '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite/$etape': {
      id: '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite/$etape'
      path: '/$etape'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/etapes-eligibilite/$etape'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRouteImport
      parentRoute: typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRoute
    }
  }
}

interface DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteChildren {
  DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRoute: typeof DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRoute
}

const DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteChildren: DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteChildren =
  {
    DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRoute:
      DysfonctionnementTesterMonEligibiliteEtapesEligibiliteEtapeRoute,
  }

const DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteWithChildren =
  DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRoute._addFileChildren(
    DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRoute:
    DysfonctionnementTesterMonEligibiliteEtapesEligibiliteRouteWithChildren,
  DysfonctionnementTesterMonEligibiliteResultatRoute:
    DysfonctionnementTesterMonEligibiliteResultatRoute,
  DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute:
    DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute,
  DysfonctionnementTesterMonEligibiliteIndexRoute:
    DysfonctionnementTesterMonEligibiliteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
