<?php

namespace MonIndemnisationJustice\Tests\Controller\Agent;

use Doctrine\ORM\EntityManagerInterface;
use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Liip\TestFixturesBundle\Services\DatabaseTools\AbstractDatabaseTool;
use MonIndemnisationJustice\DataFixtures\DossierFixture;
use MonIndemnisationJustice\Entity\Agent;
use MonIndemnisationJustice\Entity\BrisPorte;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DossierControllerTest extends WebTestCase
{
    protected KernelBrowser $client;
    protected AbstractDatabaseTool $databaseTool;
    protected EntityManagerInterface $em;

    public function setUp(): void
    {
        parent::setUp();

        $this->client = self::createClient();
        $this->databaseTool = static::getContainer()->get(DatabaseToolCollection::class)->get();
        $this->em = static::getContainer()->get(EntityManagerInterface::class);

        $this->databaseTool->loadFixtures([DossierFixture::class]);
    }

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    public function testConsulterDossier(): void
    {
        $agent = $this->em->getRepository(Agent::class)->findOneBy(['email' => 'redacteur@justice.gouv.fr']);
        $dossier = $this->em->getRepository(BrisPorte::class)->findOneBy(['reference' => 'BRI/20250101/001']);

        $this->client->loginUser($agent, 'agent');

        $this->client->request('GET', "/agent/redacteur/dossier/{$dossier->getId()}");

        $reactArguments = json_decode($this->client->getCrawler()->filter('#react-arguments')->first()->text(), true);

        $this->assertArraysSimilar([
            'id' => $dossier->getId(),
            'reference' => $dossier->getReference(),
            'etat' => $dossier->getEtatDossier()->getEtat()->value,
            'dateDepot' => null,
            'redacteur' => $agent->getId(),
            'notes' => null,
            'testEligibilite' => null,
            'dateOperation' => null,
            'estPorteBlindee' => false,
            'documents' => [],
            'corpsCourrier' => null,
            'montantIndemnisation' => null,
            'courrier' => null,
            'adresse' => [
                'ligne1' => $dossier->getAdresse()->getLigne1(),
                'ligne2' => $dossier->getAdresse()->getLigne2(),
                'codePostal' => $dossier->getAdresse()->getCodePostal(),
                'localite' => $dossier->getAdresse()->getLocalite(),
            ],
            'requerant' => [
                'civilite' => $dossier->getRequerant()->getPersonnePhysique()->getCivilite()->value,
                'nom' => $dossier->getRequerant()->getPersonnePhysique()->getNom(),
                'prenoms' => [
                    $dossier->getRequerant()->getPersonnePhysique()->getPrenom1(),
                    $dossier->getRequerant()->getPersonnePhysique()->getPrenom2(),
                    $dossier->getRequerant()->getPersonnePhysique()->getPrenom3(),
                ],
                'nomNaissance' => null,
                'courriel' => null,
                'telephone' => $dossier->getRequerant()->getPersonnePhysique()->getTelephone(),
                'dateNaissance' => $dossier->getRequerant()->getPersonnePhysique()->getDateNaissance()->getTimestamp() * 1000,
                'communeNaissance' => $dossier->getRequerant()->getPersonnePhysique()->getCommuneNaissance(),
                'paysNaissance' => null,
                'raisonSociale' => null,
                'siren' => null,
            ],
        ], $reactArguments['dossier']);
    }

    public function assertArraysSimilar(array $expected, array $actual, string $message = 'The arrays are not similar'): void
    {
        $diff = array_diff_multidimensional($actual, $expected);
        if (count($diff) > 0) {
            dump($diff);
        }
        $this->assertEmpty($diff, $message);
    }
}
