# Documentation: https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
services:
  scaleway_s3_client:
    class: 'Aws\S3\S3Client'
    arguments:
      - endpoint: '%env(resolve:SCW_HOST)%'
        credentials:
            key: '%env(resolve:SCW_ACCESS_KEY)%'
            secret: '%env(resolve:SCW_SECRET_KEY)%'
        region: '%env(resolve:SCW_REGION)%'
        http:
            connect_timeout: 2
            timeout: 5

flysystem:
  storages:
    default.storage:
      adapter: 'aws'
      options:
        client: 'scaleway_s3_client'
        bucket: '%env(resolve:SCW_BUCKET)%'
        streamReads: true
