# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        cookie_lifetime: 1209600 # 14 jours
        gc_maxlifetime: 1209600

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@develop:
    framework:
        trusted_proxies: '127.0.0.1,REMOTE_ADDR'

when@prod:
    framework:
        trusted_proxies: '127.0.0.1,%env(default::CC_REVERSE_PROXY_IPS)%'

