opctim_csp_bundle:
  # See https://github.com/opctim/symfony-csp-bundle?tab=readme-ov-file#the-always_add-option
  always_add: [ ]

  directives:
    default-src:
      - "'self'"
      - 'data:'
      - 'https:'
    base-uri:
      - "'self'"
    object-src:
      - "'self'"
    script-src:
      - "'self'"
      - 'stats.beta.gouv.fr'
      - 'sentry.incubateur.net'
      - 'client.crisp.chat'
      - 'nonce(mij-script)'
    img-src:
      - "'self'"
      - 'data:'
    style-src:
      - "'self'"
      - "'unsafe-inline'"

# For different set-ups in the dev environment
when@dev:
  opctim_csp_bundle:
    # always_add: []

    directives:
    # Add your directive overrides here
