/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as DysfonctionnementTesterMonEligibiliteIndexRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/index'
import { Route as DysfonctionnementTesterMonEligibiliteTestEligibiliteRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
import { Route as DysfonctionnementTesterMonEligibiliteResultatRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/resultat'
import { Route as DysfonctionnementTesterMonEligibilite5DiligencesRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/5-diligences'
import { Route as DysfonctionnementTesterMonEligibilite4PiecesProcedureRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure'
import { Route as DysfonctionnementTesterMonEligibilite3TypeDecisionRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/3-type-decision'
import { Route as DysfonctionnementTesterMonEligibilite2ActionContentieuseRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse'
import { Route as DysfonctionnementTesterMonEligibilite1DateDecisionRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/1-date-decision'

const DysfonctionnementTesterMonEligibiliteIndexRoute =
  DysfonctionnementTesterMonEligibiliteIndexRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/',
    path: '/dysfonctionnement/tester-mon-eligibilite/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute =
  DysfonctionnementTesterMonEligibiliteTestEligibiliteRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite',
    path: '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibiliteResultatRoute =
  DysfonctionnementTesterMonEligibiliteResultatRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/resultat',
    path: '/dysfonctionnement/tester-mon-eligibilite/resultat',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite5DiligencesRoute =
  DysfonctionnementTesterMonEligibilite5DiligencesRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/5-diligences',
    path: '/dysfonctionnement/tester-mon-eligibilite/5-diligences',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite4PiecesProcedureRoute =
  DysfonctionnementTesterMonEligibilite4PiecesProcedureRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure',
    path: '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite3TypeDecisionRoute =
  DysfonctionnementTesterMonEligibilite3TypeDecisionRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/3-type-decision',
    path: '/dysfonctionnement/tester-mon-eligibilite/3-type-decision',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite2ActionContentieuseRoute =
  DysfonctionnementTesterMonEligibilite2ActionContentieuseRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse',
    path: '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite1DateDecisionRoute =
  DysfonctionnementTesterMonEligibilite1DateDecisionRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/1-date-decision',
    path: '/dysfonctionnement/tester-mon-eligibilite/1-date-decision',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/dysfonctionnement/tester-mon-eligibilite/1-date-decision': typeof DysfonctionnementTesterMonEligibilite1DateDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse': typeof DysfonctionnementTesterMonEligibilite2ActionContentieuseRoute
  '/dysfonctionnement/tester-mon-eligibilite/3-type-decision': typeof DysfonctionnementTesterMonEligibilite3TypeDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure': typeof DysfonctionnementTesterMonEligibilite4PiecesProcedureRoute
  '/dysfonctionnement/tester-mon-eligibilite/5-diligences': typeof DysfonctionnementTesterMonEligibilite5DiligencesRoute
  '/dysfonctionnement/tester-mon-eligibilite/resultat': typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite': typeof DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute
  '/dysfonctionnement/tester-mon-eligibilite': typeof DysfonctionnementTesterMonEligibiliteIndexRoute
}
export interface FileRoutesByTo {
  '/dysfonctionnement/tester-mon-eligibilite/1-date-decision': typeof DysfonctionnementTesterMonEligibilite1DateDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse': typeof DysfonctionnementTesterMonEligibilite2ActionContentieuseRoute
  '/dysfonctionnement/tester-mon-eligibilite/3-type-decision': typeof DysfonctionnementTesterMonEligibilite3TypeDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure': typeof DysfonctionnementTesterMonEligibilite4PiecesProcedureRoute
  '/dysfonctionnement/tester-mon-eligibilite/5-diligences': typeof DysfonctionnementTesterMonEligibilite5DiligencesRoute
  '/dysfonctionnement/tester-mon-eligibilite/resultat': typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite': typeof DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute
  '/dysfonctionnement/tester-mon-eligibilite': typeof DysfonctionnementTesterMonEligibiliteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dysfonctionnement/tester-mon-eligibilite/1-date-decision': typeof DysfonctionnementTesterMonEligibilite1DateDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse': typeof DysfonctionnementTesterMonEligibilite2ActionContentieuseRoute
  '/dysfonctionnement/tester-mon-eligibilite/3-type-decision': typeof DysfonctionnementTesterMonEligibilite3TypeDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure': typeof DysfonctionnementTesterMonEligibilite4PiecesProcedureRoute
  '/dysfonctionnement/tester-mon-eligibilite/5-diligences': typeof DysfonctionnementTesterMonEligibilite5DiligencesRoute
  '/dysfonctionnement/tester-mon-eligibilite/resultat': typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite': typeof DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute
  '/dysfonctionnement/tester-mon-eligibilite/': typeof DysfonctionnementTesterMonEligibiliteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dysfonctionnement/tester-mon-eligibilite/1-date-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse'
    | '/dysfonctionnement/tester-mon-eligibilite/3-type-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure'
    | '/dysfonctionnement/tester-mon-eligibilite/5-diligences'
    | '/dysfonctionnement/tester-mon-eligibilite/resultat'
    | '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dysfonctionnement/tester-mon-eligibilite/1-date-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse'
    | '/dysfonctionnement/tester-mon-eligibilite/3-type-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure'
    | '/dysfonctionnement/tester-mon-eligibilite/5-diligences'
    | '/dysfonctionnement/tester-mon-eligibilite/resultat'
    | '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite'
  id:
    | '__root__'
    | '/dysfonctionnement/tester-mon-eligibilite/1-date-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse'
    | '/dysfonctionnement/tester-mon-eligibilite/3-type-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure'
    | '/dysfonctionnement/tester-mon-eligibilite/5-diligences'
    | '/dysfonctionnement/tester-mon-eligibilite/resultat'
    | '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
    | '/dysfonctionnement/tester-mon-eligibilite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DysfonctionnementTesterMonEligibilite1DateDecisionRoute: typeof DysfonctionnementTesterMonEligibilite1DateDecisionRoute
  DysfonctionnementTesterMonEligibilite2ActionContentieuseRoute: typeof DysfonctionnementTesterMonEligibilite2ActionContentieuseRoute
  DysfonctionnementTesterMonEligibilite3TypeDecisionRoute: typeof DysfonctionnementTesterMonEligibilite3TypeDecisionRoute
  DysfonctionnementTesterMonEligibilite4PiecesProcedureRoute: typeof DysfonctionnementTesterMonEligibilite4PiecesProcedureRoute
  DysfonctionnementTesterMonEligibilite5DiligencesRoute: typeof DysfonctionnementTesterMonEligibilite5DiligencesRoute
  DysfonctionnementTesterMonEligibiliteResultatRoute: typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute: typeof DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute
  DysfonctionnementTesterMonEligibiliteIndexRoute: typeof DysfonctionnementTesterMonEligibiliteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dysfonctionnement/tester-mon-eligibilite/': {
      id: '/dysfonctionnement/tester-mon-eligibilite/'
      path: '/dysfonctionnement/tester-mon-eligibilite'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibiliteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite': {
      id: '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
      path: '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/test-eligibilite'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibiliteTestEligibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/resultat': {
      id: '/dysfonctionnement/tester-mon-eligibilite/resultat'
      path: '/dysfonctionnement/tester-mon-eligibilite/resultat'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/resultat'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibiliteResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/5-diligences': {
      id: '/dysfonctionnement/tester-mon-eligibilite/5-diligences'
      path: '/dysfonctionnement/tester-mon-eligibilite/5-diligences'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/5-diligences'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite5DiligencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure': {
      id: '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure'
      path: '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/4-pieces-procedure'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite4PiecesProcedureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/3-type-decision': {
      id: '/dysfonctionnement/tester-mon-eligibilite/3-type-decision'
      path: '/dysfonctionnement/tester-mon-eligibilite/3-type-decision'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/3-type-decision'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite3TypeDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse': {
      id: '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse'
      path: '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/2-action-contentieuse'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite2ActionContentieuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/1-date-decision': {
      id: '/dysfonctionnement/tester-mon-eligibilite/1-date-decision'
      path: '/dysfonctionnement/tester-mon-eligibilite/1-date-decision'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/1-date-decision'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite1DateDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DysfonctionnementTesterMonEligibilite1DateDecisionRoute:
    DysfonctionnementTesterMonEligibilite1DateDecisionRoute,
  DysfonctionnementTesterMonEligibilite2ActionContentieuseRoute:
    DysfonctionnementTesterMonEligibilite2ActionContentieuseRoute,
  DysfonctionnementTesterMonEligibilite3TypeDecisionRoute:
    DysfonctionnementTesterMonEligibilite3TypeDecisionRoute,
  DysfonctionnementTesterMonEligibilite4PiecesProcedureRoute:
    DysfonctionnementTesterMonEligibilite4PiecesProcedureRoute,
  DysfonctionnementTesterMonEligibilite5DiligencesRoute:
    DysfonctionnementTesterMonEligibilite5DiligencesRoute,
  DysfonctionnementTesterMonEligibiliteResultatRoute:
    DysfonctionnementTesterMonEligibiliteResultatRoute,
  DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute:
    DysfonctionnementTesterMonEligibiliteTestEligibiliteRoute,
  DysfonctionnementTesterMonEligibiliteIndexRoute:
    DysfonctionnementTesterMonEligibiliteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
