/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as DysfonctionnementIndexRouteImport } from './../routes/dysfonctionnement/index'
import { Route as DysfonctionnementTesterMonEligibiliteIndexRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/index'
import { Route as DysfonctionnementTesterMonEligibiliteResultatRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/resultat'
import { Route as DysfonctionnementTesterMonEligibilite6DiligencesRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/6-diligences'
import { Route as DysfonctionnementTesterMonEligibilite5PiecesProcedureRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure'
import { Route as DysfonctionnementTesterMonEligibilite4TypeDecisionRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/4-type-decision'
import { Route as DysfonctionnementTesterMonEligibilite3ActionContentieuseRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse'
import { Route as DysfonctionnementTesterMonEligibilite2DateDecisionRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/2-date-decision'
import { Route as DysfonctionnementTesterMonEligibilite1EtatProcedureRouteImport } from './../routes/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure'
import { Route as DysfonctionnementSIdentifierUsagersRouteImport } from './../routes/dysfonctionnement/s-identifier/usagers'
import { Route as DysfonctionnementSIdentifierAvocatsRouteImport } from './../routes/dysfonctionnement/s-identifier/avocats'

const DysfonctionnementIndexRoute = DysfonctionnementIndexRouteImport.update({
  id: '/dysfonctionnement/',
  path: '/dysfonctionnement/',
  getParentRoute: () => rootRouteImport,
} as any)
const DysfonctionnementTesterMonEligibiliteIndexRoute =
  DysfonctionnementTesterMonEligibiliteIndexRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/',
    path: '/dysfonctionnement/tester-mon-eligibilite/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibiliteResultatRoute =
  DysfonctionnementTesterMonEligibiliteResultatRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/resultat',
    path: '/dysfonctionnement/tester-mon-eligibilite/resultat',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite6DiligencesRoute =
  DysfonctionnementTesterMonEligibilite6DiligencesRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/6-diligences',
    path: '/dysfonctionnement/tester-mon-eligibilite/6-diligences',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite5PiecesProcedureRoute =
  DysfonctionnementTesterMonEligibilite5PiecesProcedureRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure',
    path: '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite4TypeDecisionRoute =
  DysfonctionnementTesterMonEligibilite4TypeDecisionRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/4-type-decision',
    path: '/dysfonctionnement/tester-mon-eligibilite/4-type-decision',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite3ActionContentieuseRoute =
  DysfonctionnementTesterMonEligibilite3ActionContentieuseRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse',
    path: '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite2DateDecisionRoute =
  DysfonctionnementTesterMonEligibilite2DateDecisionRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/2-date-decision',
    path: '/dysfonctionnement/tester-mon-eligibilite/2-date-decision',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementTesterMonEligibilite1EtatProcedureRoute =
  DysfonctionnementTesterMonEligibilite1EtatProcedureRouteImport.update({
    id: '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure',
    path: '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementSIdentifierUsagersRoute =
  DysfonctionnementSIdentifierUsagersRouteImport.update({
    id: '/dysfonctionnement/s-identifier/usagers',
    path: '/dysfonctionnement/s-identifier/usagers',
    getParentRoute: () => rootRouteImport,
  } as any)
const DysfonctionnementSIdentifierAvocatsRoute =
  DysfonctionnementSIdentifierAvocatsRouteImport.update({
    id: '/dysfonctionnement/s-identifier/avocats',
    path: '/dysfonctionnement/s-identifier/avocats',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/dysfonctionnement': typeof DysfonctionnementIndexRoute
  '/dysfonctionnement/s-identifier/avocats': typeof DysfonctionnementSIdentifierAvocatsRoute
  '/dysfonctionnement/s-identifier/usagers': typeof DysfonctionnementSIdentifierUsagersRoute
  '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure': typeof DysfonctionnementTesterMonEligibilite1EtatProcedureRoute
  '/dysfonctionnement/tester-mon-eligibilite/2-date-decision': typeof DysfonctionnementTesterMonEligibilite2DateDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse': typeof DysfonctionnementTesterMonEligibilite3ActionContentieuseRoute
  '/dysfonctionnement/tester-mon-eligibilite/4-type-decision': typeof DysfonctionnementTesterMonEligibilite4TypeDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure': typeof DysfonctionnementTesterMonEligibilite5PiecesProcedureRoute
  '/dysfonctionnement/tester-mon-eligibilite/6-diligences': typeof DysfonctionnementTesterMonEligibilite6DiligencesRoute
  '/dysfonctionnement/tester-mon-eligibilite/resultat': typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  '/dysfonctionnement/tester-mon-eligibilite': typeof DysfonctionnementTesterMonEligibiliteIndexRoute
}
export interface FileRoutesByTo {
  '/dysfonctionnement': typeof DysfonctionnementIndexRoute
  '/dysfonctionnement/s-identifier/avocats': typeof DysfonctionnementSIdentifierAvocatsRoute
  '/dysfonctionnement/s-identifier/usagers': typeof DysfonctionnementSIdentifierUsagersRoute
  '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure': typeof DysfonctionnementTesterMonEligibilite1EtatProcedureRoute
  '/dysfonctionnement/tester-mon-eligibilite/2-date-decision': typeof DysfonctionnementTesterMonEligibilite2DateDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse': typeof DysfonctionnementTesterMonEligibilite3ActionContentieuseRoute
  '/dysfonctionnement/tester-mon-eligibilite/4-type-decision': typeof DysfonctionnementTesterMonEligibilite4TypeDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure': typeof DysfonctionnementTesterMonEligibilite5PiecesProcedureRoute
  '/dysfonctionnement/tester-mon-eligibilite/6-diligences': typeof DysfonctionnementTesterMonEligibilite6DiligencesRoute
  '/dysfonctionnement/tester-mon-eligibilite/resultat': typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  '/dysfonctionnement/tester-mon-eligibilite': typeof DysfonctionnementTesterMonEligibiliteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dysfonctionnement/': typeof DysfonctionnementIndexRoute
  '/dysfonctionnement/s-identifier/avocats': typeof DysfonctionnementSIdentifierAvocatsRoute
  '/dysfonctionnement/s-identifier/usagers': typeof DysfonctionnementSIdentifierUsagersRoute
  '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure': typeof DysfonctionnementTesterMonEligibilite1EtatProcedureRoute
  '/dysfonctionnement/tester-mon-eligibilite/2-date-decision': typeof DysfonctionnementTesterMonEligibilite2DateDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse': typeof DysfonctionnementTesterMonEligibilite3ActionContentieuseRoute
  '/dysfonctionnement/tester-mon-eligibilite/4-type-decision': typeof DysfonctionnementTesterMonEligibilite4TypeDecisionRoute
  '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure': typeof DysfonctionnementTesterMonEligibilite5PiecesProcedureRoute
  '/dysfonctionnement/tester-mon-eligibilite/6-diligences': typeof DysfonctionnementTesterMonEligibilite6DiligencesRoute
  '/dysfonctionnement/tester-mon-eligibilite/resultat': typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  '/dysfonctionnement/tester-mon-eligibilite/': typeof DysfonctionnementTesterMonEligibiliteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dysfonctionnement'
    | '/dysfonctionnement/s-identifier/avocats'
    | '/dysfonctionnement/s-identifier/usagers'
    | '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure'
    | '/dysfonctionnement/tester-mon-eligibilite/2-date-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse'
    | '/dysfonctionnement/tester-mon-eligibilite/4-type-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure'
    | '/dysfonctionnement/tester-mon-eligibilite/6-diligences'
    | '/dysfonctionnement/tester-mon-eligibilite/resultat'
    | '/dysfonctionnement/tester-mon-eligibilite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dysfonctionnement'
    | '/dysfonctionnement/s-identifier/avocats'
    | '/dysfonctionnement/s-identifier/usagers'
    | '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure'
    | '/dysfonctionnement/tester-mon-eligibilite/2-date-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse'
    | '/dysfonctionnement/tester-mon-eligibilite/4-type-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure'
    | '/dysfonctionnement/tester-mon-eligibilite/6-diligences'
    | '/dysfonctionnement/tester-mon-eligibilite/resultat'
    | '/dysfonctionnement/tester-mon-eligibilite'
  id:
    | '__root__'
    | '/dysfonctionnement/'
    | '/dysfonctionnement/s-identifier/avocats'
    | '/dysfonctionnement/s-identifier/usagers'
    | '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure'
    | '/dysfonctionnement/tester-mon-eligibilite/2-date-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse'
    | '/dysfonctionnement/tester-mon-eligibilite/4-type-decision'
    | '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure'
    | '/dysfonctionnement/tester-mon-eligibilite/6-diligences'
    | '/dysfonctionnement/tester-mon-eligibilite/resultat'
    | '/dysfonctionnement/tester-mon-eligibilite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DysfonctionnementIndexRoute: typeof DysfonctionnementIndexRoute
  DysfonctionnementSIdentifierAvocatsRoute: typeof DysfonctionnementSIdentifierAvocatsRoute
  DysfonctionnementSIdentifierUsagersRoute: typeof DysfonctionnementSIdentifierUsagersRoute
  DysfonctionnementTesterMonEligibilite1EtatProcedureRoute: typeof DysfonctionnementTesterMonEligibilite1EtatProcedureRoute
  DysfonctionnementTesterMonEligibilite2DateDecisionRoute: typeof DysfonctionnementTesterMonEligibilite2DateDecisionRoute
  DysfonctionnementTesterMonEligibilite3ActionContentieuseRoute: typeof DysfonctionnementTesterMonEligibilite3ActionContentieuseRoute
  DysfonctionnementTesterMonEligibilite4TypeDecisionRoute: typeof DysfonctionnementTesterMonEligibilite4TypeDecisionRoute
  DysfonctionnementTesterMonEligibilite5PiecesProcedureRoute: typeof DysfonctionnementTesterMonEligibilite5PiecesProcedureRoute
  DysfonctionnementTesterMonEligibilite6DiligencesRoute: typeof DysfonctionnementTesterMonEligibilite6DiligencesRoute
  DysfonctionnementTesterMonEligibiliteResultatRoute: typeof DysfonctionnementTesterMonEligibiliteResultatRoute
  DysfonctionnementTesterMonEligibiliteIndexRoute: typeof DysfonctionnementTesterMonEligibiliteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dysfonctionnement/': {
      id: '/dysfonctionnement/'
      path: '/dysfonctionnement'
      fullPath: '/dysfonctionnement'
      preLoaderRoute: typeof DysfonctionnementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/': {
      id: '/dysfonctionnement/tester-mon-eligibilite/'
      path: '/dysfonctionnement/tester-mon-eligibilite'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibiliteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/resultat': {
      id: '/dysfonctionnement/tester-mon-eligibilite/resultat'
      path: '/dysfonctionnement/tester-mon-eligibilite/resultat'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/resultat'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibiliteResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/6-diligences': {
      id: '/dysfonctionnement/tester-mon-eligibilite/6-diligences'
      path: '/dysfonctionnement/tester-mon-eligibilite/6-diligences'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/6-diligences'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite6DiligencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure': {
      id: '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure'
      path: '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/5-pieces-procedure'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite5PiecesProcedureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/4-type-decision': {
      id: '/dysfonctionnement/tester-mon-eligibilite/4-type-decision'
      path: '/dysfonctionnement/tester-mon-eligibilite/4-type-decision'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/4-type-decision'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite4TypeDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse': {
      id: '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse'
      path: '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/3-action-contentieuse'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite3ActionContentieuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/2-date-decision': {
      id: '/dysfonctionnement/tester-mon-eligibilite/2-date-decision'
      path: '/dysfonctionnement/tester-mon-eligibilite/2-date-decision'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/2-date-decision'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite2DateDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure': {
      id: '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure'
      path: '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure'
      fullPath: '/dysfonctionnement/tester-mon-eligibilite/1-etat-procedure'
      preLoaderRoute: typeof DysfonctionnementTesterMonEligibilite1EtatProcedureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/s-identifier/usagers': {
      id: '/dysfonctionnement/s-identifier/usagers'
      path: '/dysfonctionnement/s-identifier/usagers'
      fullPath: '/dysfonctionnement/s-identifier/usagers'
      preLoaderRoute: typeof DysfonctionnementSIdentifierUsagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dysfonctionnement/s-identifier/avocats': {
      id: '/dysfonctionnement/s-identifier/avocats'
      path: '/dysfonctionnement/s-identifier/avocats'
      fullPath: '/dysfonctionnement/s-identifier/avocats'
      preLoaderRoute: typeof DysfonctionnementSIdentifierAvocatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DysfonctionnementIndexRoute: DysfonctionnementIndexRoute,
  DysfonctionnementSIdentifierAvocatsRoute:
    DysfonctionnementSIdentifierAvocatsRoute,
  DysfonctionnementSIdentifierUsagersRoute:
    DysfonctionnementSIdentifierUsagersRoute,
  DysfonctionnementTesterMonEligibilite1EtatProcedureRoute:
    DysfonctionnementTesterMonEligibilite1EtatProcedureRoute,
  DysfonctionnementTesterMonEligibilite2DateDecisionRoute:
    DysfonctionnementTesterMonEligibilite2DateDecisionRoute,
  DysfonctionnementTesterMonEligibilite3ActionContentieuseRoute:
    DysfonctionnementTesterMonEligibilite3ActionContentieuseRoute,
  DysfonctionnementTesterMonEligibilite4TypeDecisionRoute:
    DysfonctionnementTesterMonEligibilite4TypeDecisionRoute,
  DysfonctionnementTesterMonEligibilite5PiecesProcedureRoute:
    DysfonctionnementTesterMonEligibilite5PiecesProcedureRoute,
  DysfonctionnementTesterMonEligibilite6DiligencesRoute:
    DysfonctionnementTesterMonEligibilite6DiligencesRoute,
  DysfonctionnementTesterMonEligibiliteResultatRoute:
    DysfonctionnementTesterMonEligibiliteResultatRoute,
  DysfonctionnementTesterMonEligibiliteIndexRoute:
    DysfonctionnementTesterMonEligibiliteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
