sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        ignore_exceptions:
            - 'Symfony\Component\ErrorHandler\Error\FatalError'
            - 'Symfony\Component\Debug\Exception\FatalErrorException'