/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as RequerantIndexRouteImport } from './../routes/requerant/index'
import { Route as RequerantMesDemandesRouteImport } from './../routes/requerant/mes-demandes'
import { Route as RequerantDossierBrisDePorteReferenceIndexRouteImport } from './../routes/requerant/dossier/bris-de-porte/$reference/index'
import { Route as RequerantDossierBrisDePorteReference3PiecesJointesRouteImport } from './../routes/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes'
import { Route as RequerantDossierBrisDePorteReference2InfosRequerantRouteImport } from './../routes/requerant/dossier/bris-de-porte/$reference/2-infos-requerant'
import { Route as RequerantDossierBrisDePorteReference1BrisPorteRouteImport } from './../routes/requerant/dossier/bris-de-porte/$reference/1-bris-porte'

const RequerantIndexRoute = RequerantIndexRouteImport.update({
  id: '/requerant/',
  path: '/requerant/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequerantMesDemandesRoute = RequerantMesDemandesRouteImport.update({
  id: '/requerant/mes-demandes',
  path: '/requerant/mes-demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const RequerantDossierBrisDePorteReferenceIndexRoute =
  RequerantDossierBrisDePorteReferenceIndexRouteImport.update({
    id: '/requerant/dossier/bris-de-porte/$reference/',
    path: '/requerant/dossier/bris-de-porte/$reference/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RequerantDossierBrisDePorteReference3PiecesJointesRoute =
  RequerantDossierBrisDePorteReference3PiecesJointesRouteImport.update({
    id: '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes',
    path: '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes',
    getParentRoute: () => rootRouteImport,
  } as any)
const RequerantDossierBrisDePorteReference2InfosRequerantRoute =
  RequerantDossierBrisDePorteReference2InfosRequerantRouteImport.update({
    id: '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant',
    path: '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant',
    getParentRoute: () => rootRouteImport,
  } as any)
const RequerantDossierBrisDePorteReference1BrisPorteRoute =
  RequerantDossierBrisDePorteReference1BrisPorteRouteImport.update({
    id: '/requerant/dossier/bris-de-porte/$reference/1-bris-porte',
    path: '/requerant/dossier/bris-de-porte/$reference/1-bris-porte',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/requerant/mes-demandes': typeof RequerantMesDemandesRoute
  '/requerant': typeof RequerantIndexRoute
  '/requerant/dossier/bris-de-porte/$reference/1-bris-porte': typeof RequerantDossierBrisDePorteReference1BrisPorteRoute
  '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant': typeof RequerantDossierBrisDePorteReference2InfosRequerantRoute
  '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes': typeof RequerantDossierBrisDePorteReference3PiecesJointesRoute
  '/requerant/dossier/bris-de-porte/$reference': typeof RequerantDossierBrisDePorteReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/requerant/mes-demandes': typeof RequerantMesDemandesRoute
  '/requerant': typeof RequerantIndexRoute
  '/requerant/dossier/bris-de-porte/$reference/1-bris-porte': typeof RequerantDossierBrisDePorteReference1BrisPorteRoute
  '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant': typeof RequerantDossierBrisDePorteReference2InfosRequerantRoute
  '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes': typeof RequerantDossierBrisDePorteReference3PiecesJointesRoute
  '/requerant/dossier/bris-de-porte/$reference': typeof RequerantDossierBrisDePorteReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/requerant/mes-demandes': typeof RequerantMesDemandesRoute
  '/requerant/': typeof RequerantIndexRoute
  '/requerant/dossier/bris-de-porte/$reference/1-bris-porte': typeof RequerantDossierBrisDePorteReference1BrisPorteRoute
  '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant': typeof RequerantDossierBrisDePorteReference2InfosRequerantRoute
  '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes': typeof RequerantDossierBrisDePorteReference3PiecesJointesRoute
  '/requerant/dossier/bris-de-porte/$reference/': typeof RequerantDossierBrisDePorteReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/requerant/mes-demandes'
    | '/requerant'
    | '/requerant/dossier/bris-de-porte/$reference/1-bris-porte'
    | '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant'
    | '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes'
    | '/requerant/dossier/bris-de-porte/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/requerant/mes-demandes'
    | '/requerant'
    | '/requerant/dossier/bris-de-porte/$reference/1-bris-porte'
    | '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant'
    | '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes'
    | '/requerant/dossier/bris-de-porte/$reference'
  id:
    | '__root__'
    | '/requerant/mes-demandes'
    | '/requerant/'
    | '/requerant/dossier/bris-de-porte/$reference/1-bris-porte'
    | '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant'
    | '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes'
    | '/requerant/dossier/bris-de-porte/$reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RequerantMesDemandesRoute: typeof RequerantMesDemandesRoute
  RequerantIndexRoute: typeof RequerantIndexRoute
  RequerantDossierBrisDePorteReference1BrisPorteRoute: typeof RequerantDossierBrisDePorteReference1BrisPorteRoute
  RequerantDossierBrisDePorteReference2InfosRequerantRoute: typeof RequerantDossierBrisDePorteReference2InfosRequerantRoute
  RequerantDossierBrisDePorteReference3PiecesJointesRoute: typeof RequerantDossierBrisDePorteReference3PiecesJointesRoute
  RequerantDossierBrisDePorteReferenceIndexRoute: typeof RequerantDossierBrisDePorteReferenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/requerant/': {
      id: '/requerant/'
      path: '/requerant'
      fullPath: '/requerant'
      preLoaderRoute: typeof RequerantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requerant/mes-demandes': {
      id: '/requerant/mes-demandes'
      path: '/requerant/mes-demandes'
      fullPath: '/requerant/mes-demandes'
      preLoaderRoute: typeof RequerantMesDemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requerant/dossier/bris-de-porte/$reference/': {
      id: '/requerant/dossier/bris-de-porte/$reference/'
      path: '/requerant/dossier/bris-de-porte/$reference'
      fullPath: '/requerant/dossier/bris-de-porte/$reference'
      preLoaderRoute: typeof RequerantDossierBrisDePorteReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes': {
      id: '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes'
      path: '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes'
      fullPath: '/requerant/dossier/bris-de-porte/$reference/3-pieces-jointes'
      preLoaderRoute: typeof RequerantDossierBrisDePorteReference3PiecesJointesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant': {
      id: '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant'
      path: '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant'
      fullPath: '/requerant/dossier/bris-de-porte/$reference/2-infos-requerant'
      preLoaderRoute: typeof RequerantDossierBrisDePorteReference2InfosRequerantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requerant/dossier/bris-de-porte/$reference/1-bris-porte': {
      id: '/requerant/dossier/bris-de-porte/$reference/1-bris-porte'
      path: '/requerant/dossier/bris-de-porte/$reference/1-bris-porte'
      fullPath: '/requerant/dossier/bris-de-porte/$reference/1-bris-porte'
      preLoaderRoute: typeof RequerantDossierBrisDePorteReference1BrisPorteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  RequerantMesDemandesRoute: RequerantMesDemandesRoute,
  RequerantIndexRoute: RequerantIndexRoute,
  RequerantDossierBrisDePorteReference1BrisPorteRoute:
    RequerantDossierBrisDePorteReference1BrisPorteRoute,
  RequerantDossierBrisDePorteReference2InfosRequerantRoute:
    RequerantDossierBrisDePorteReference2InfosRequerantRoute,
  RequerantDossierBrisDePorteReference3PiecesJointesRoute:
    RequerantDossierBrisDePorteReference3PiecesJointesRoute,
  RequerantDossierBrisDePorteReferenceIndexRoute:
    RequerantDossierBrisDePorteReferenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
