<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504080640 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajustements liés à la montée de version de Doctrine';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE personne_morale_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personne_physique_id_seq CASCADE');
        $this->addSql('ALTER TABLE adresse ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE adresse ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE agents ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE agents ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE agents ALTER fournisseur_identite_uid TYPE VARCHAR');
        $this->addSql('COMMENT ON COLUMN agents.roles IS \'\'');
        $this->addSql('COMMENT ON COLUMN bris_porte.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN brouillons_declaration_fdo_bris_porte.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN brouillons_declaration_fdo_bris_porte.date_creation IS \'\'');
        $this->addSql('ALTER TABLE coordonnees_requerant ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE coordonnees_requerant ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.procedure_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.date_operation IS \'\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.date_creation IS \'\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.date_soumission IS \'\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.date_suppression IS \'\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.bris_porte_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN declaration_fdo_bris_porte_pieces_jointes.declaration_id IS \'\'');
        $this->addSql('ALTER TABLE document ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE document ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE document ALTER date_ajout SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('COMMENT ON COLUMN document.date_validation IS \'\'');
        $this->addSql('COMMENT ON COLUMN document.date_ajout IS \'\'');
        $this->addSql('COMMENT ON COLUMN document.date_derniere_modification IS \'\'');
        $this->addSql('ALTER TABLE dossier_etats ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dossier_etats ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN dossier_etats.date IS \'\'');
        $this->addSql('ALTER TABLE dossiers ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dossiers ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN dossiers.bris_porte_id IS \'\'');
        $this->addSql('ALTER TABLE eligibilite_tests ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE eligibilite_tests ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE geo_codes_postaux ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE geo_codes_postaux ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN personnes.id IS \'\'');
        $this->addSql('ALTER TABLE personnes_morales ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE personnes_morales ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN personnes_morales.representant_legal_id IS \'\'');
        $this->addSql('ALTER TABLE personnes_physiques ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE personnes_physiques ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN personnes_physiques.personne_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN procedures_judiciaires.id IS \'\'');
        $this->addSql('ALTER TABLE usagers ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE usagers ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN usagers.roles IS \'\'');
        $this->addSql('COMMENT ON COLUMN usagers.personne_id IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE personne_morale_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personne_physique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('ALTER TABLE adresse ALTER id SET DEFAULT nextval(\'adresse_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE adresse ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE agents ALTER id SET DEFAULT nextval(\'agents_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE agents ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE agents ALTER fournisseur_identite_uid TYPE VARCHAR(255)');
        $this->addSql('COMMENT ON COLUMN agents.roles IS \'(DC2Type:simple_array)\'');
        $this->addSql('COMMENT ON COLUMN bris_porte.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN brouillons_declaration_fdo_bris_porte.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN brouillons_declaration_fdo_bris_porte.date_creation IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE coordonnees_requerant ALTER id SET DEFAULT nextval(\'coordonnees_requerant_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE coordonnees_requerant ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN declaration_fdo_bris_porte_pieces_jointes.declaration_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.date_operation IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.date_creation IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.date_soumission IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.date_suppression IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.procedure_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN declarations_fdo_bris_porte.bris_porte_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE document ALTER id SET DEFAULT nextval(\'document_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE document ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE document ALTER date_ajout SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('COMMENT ON COLUMN document.date_validation IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document.date_ajout IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document.date_derniere_modification IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE dossier_etats ALTER id SET DEFAULT nextval(\'dossier_etats_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dossier_etats ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN dossier_etats.date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE dossiers ALTER id SET DEFAULT nextval(\'dossiers_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dossiers ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN dossiers.bris_porte_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE eligibilite_tests ALTER id SET DEFAULT nextval(\'eligibilite_tests_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE eligibilite_tests ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE geo_codes_postaux ALTER id SET DEFAULT nextval(\'geo_codes_postaux_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE geo_codes_postaux ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN personnes.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE personnes_morales ALTER id SET DEFAULT nextval(\'personne_morale_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE personnes_morales ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN personnes_morales.representant_legal_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE personnes_physiques ALTER id SET DEFAULT nextval(\'personne_physique_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE personnes_physiques ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN personnes_physiques.personne_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN procedures_judiciaires.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE usagers ALTER id SET DEFAULT nextval(\'usagers_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE usagers ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN usagers.roles IS \'(DC2Type:simple_array)\'');
        $this->addSql('COMMENT ON COLUMN usagers.personne_id IS \'(DC2Type:uuid)\'');
    }
}
