<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616092141 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajouter la table dysfonctionnement_test_eligibilite';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dysfonctionnement_test_eligibilite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, procedure_terminee BOOLEAN DEFAULT NULL, date_decision DATE DEFAULT NULL, a_une_action_contentieuse BOOLEAN DEFAULT NULL, types_decision JSON DEFAULT NULL, pieces_procedure JSON DEFAULT NULL, preuves_diligences BOOLEAN DEFAULT NULL, date_soumission TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usager_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B29AE0F74F36F0FC ON dysfonctionnement_test_eligibilite (usager_id)');
        $this->addSql('ALTER TABLE dysfonctionnement_test_eligibilite ADD CONSTRAINT FK_B29AE0F74F36F0FC FOREIGN KEY (usager_id) REFERENCES usagers (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_881877c16a333750 RENAME TO IDX_6AD6C7C46A333750');
        $this->addSql('ALTER INDEX idx_881877c14f36f0fc RENAME TO IDX_6AD6C7C44F36F0FC');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dysfonctionnement_test_eligibilite DROP CONSTRAINT FK_B29AE0F74F36F0FC');
        $this->addSql('DROP TABLE dysfonctionnement_test_eligibilite');
        $this->addSql('ALTER INDEX idx_6ad6c7c46a333750 RENAME TO idx_881877c16a333750');
        $this->addSql('ALTER INDEX idx_6ad6c7c44f36f0fc RENAME TO idx_881877c14f36f0fc');
    }
}
