<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250103084342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crétion de la table geo_pays';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE geo_pays (code VARCHAR(3) NOT NULL, nom VARCHAR(255) NOT NULL, est_france BOOLEAN NOT NULL, PRIMARY KEY(code))');
        $this->addSql(<<<SQL
INSERT INTO geo_pays (code, nom, est_france) VALUES
('BEL','Belgique', false),
('BOL','Bolivie', false),
('COM','Comores', false),
('CHE','Suisse', false),
('GHA','Ghana', false),
('IRN','Iran', false),
('IRQ','Irak', false),
('JAM','Jamaïque', false),
('NLD','Pays-Bas', false),
('POL','Pologne', false),
('VAT','Vatican', false),
('AFG','Afghanistan', false),
('DZA','Algérie', false),
('HKG','Hong Kong (Chine)', false),
('LAO','Laos', false),
('NRU','Nauru', false),
('TKM','Turkménistan', false),
('ZMB','Zambie', false),
('AUS','Australie', false),
('BHS','Bahamas', false),
('BIH','Bosnie-Herzégovine', false),
('CZE','République tchèque', false),
('FRA','France', true),
('KOR','Corée du Sud', false),
('PHL','Philippines', false),
('VCT','Saint-Vincent-et-les-Grenadines', false),
('ARM','Arménie', false),
('AZE','Azerbaïdjan', false),
('BDI','Burundi', false),
('BGD','Bangladesh', false),
('ECU','Equateur', false),
('ETH','Ethiopie', false),
('GAB','Gabon', false),
('GMB','Gambie', false),
('HTI','Haïti', false),
('KIR','Kiribati', false),
('MAC','Macao (Chine)', false),
('MMR','Birmanie', false),
('PRI','Porto Rico', false),
('QAT','Qatar', false),
('SVK','Slovaquie', false),
('TGO','Togo', false),
('UKR','Ukraine', false),
('GRC','Grèce', false),
('MOZ','Mozambique', false),
('MUS','Ile Maurice', false),
('BWA','Botswana', false),
('CAF','République centrafricaine', false),
('FIN','Finlande', false),
('KAZ','Kazakhstan', false),
('MHL','Îles Marshall', false),
('MNE','Monténégro', false),
('MYS','Malaisie', false),
('NPL','Népal', false),
('NZL','Nouvelle-Zélande', false),
('PER','Pérou', false),
('USA','Etats-Unis', false),
('YEM','Yémen', false),
('CMR','Cameroun', false),
('CUB','Cuba', false),
('DOM','République dominicaine', false),
('ITA','Italie', false),
('LBR','Liberia', false),
('SWE','Suède', false),
('TUN','Tunisie', false),
('WSM','Samoa', false),
('CUW','Curaçao', false),
('DNK','Danemark', false),
('IDN','Indonésie', false),
('SGP','Singapour', false),
('SLV','Salvador', false),
('UGA','Uganda', false),
('URY','Uruguay', false),
('VEN','Venezuela', false),
('DEU','Allemagne', false),
('GUM','Guam', false),
('MKD','Macédoine du Nord', false),
('MWI','Malawi', false),
('PAK','Pakistan', false),
('PRT','Portugal', false),
('BGR','Bulgarie', false),
('BRN','Brunei', false),
('CYP','Chypre', false),
('FSM','Micronésie', false),
('MAR','Maroc', false),
('MDA','Moldavie', false),
('MDG','Madagascar', false),
('MNG','Mongolie', false),
('SLE','Sierra Leone', false),
('TLS','Timor oriental', false),
('VNM','Viêt Nam', false),
('AGO','Angola', false),
('BLZ','Belize', false),
('HUN','Hongrie', false),
('IRL','Irlande', false),
('KWT','Koweït', false),
('MDV','Maldives', false),
('NER','Niger', false),
('NIC','Nicaragua', false),
('PSE','Territoires palestiniens', false),
('TWN','Taïwan', false),
('ARG','Argentine', false),
('COL','Colombie', false),
('JOR','Jordanie', false),
('NAM','Namibie', false),
('SRB','Serbie', false),
('TJK','Tadjikistan', false),
('CPV','Cap Vert', false),
('GEO','Géorgie', false),
('KOS','Kosovo', false),
('LUX','Luxembourg', false),
('OMN','Oman', false),
('RUS','Russie', false),
('SOM','Somalie', false),
('SYC','Seychelles', false),
('TCD','Tchad', false),
('TUV','Tuvalu', false),
('AND','Andorre', false),
('BHR','Bahreïn', false),
('BRA','Brésil', false),
('DJI','Djibouti', false),
('DMA','Dominique', false),
('EST','Estonie', false),
('GTM','Guatemala', false),
('ISR','Israël', false),
('MCO','Monaco', false),
('MLT','Malte', false),
('SEN','Sénégal', false),
('SXM','Saint Martin (partie néerlandaise)', false),
('VUT','Vanuatu', false),
('CAN','Canada', false),
('MLI','Mali', false),
('MNP','Îles Mariannes du Nord', false),
('SDN','Soudan', false),
('BRB','Barbade', false),
('FJI','Fidji', false),
('KGZ','Kirghizistan', false),
('MAF','Saint-Martin (partie française)', false),
('MRT','Mauritanie', false),
('ZWE','Zimbabwe', false),
('CA', 'QC,Québec', false),
('CHL','Chili', false),
('HRV','Croatie', false),
('SAU','Arabie Saoudite', false),
('ASM','Samoa américaines', false),
('BMU','Bermudes', false),
('COD','Congo (Rép. dém.)', false),
('CRI','Costa Rica', false),
('GIN','Guinée', false),
('IMN','Île de Man', false),
('JPN','Japon', false),
('SLB','Îles Salomon', false),
('SMR','Saint-Marin', false),
('SUR','Suriname', false),
('TCA','Îles Turques-et-Caïques', false),
('ATG','Antigua-et-Barbuda', false),
('COG','Congo', false),
('HND','Honduras', false),
('KNA','Saint-Christophe-et-Niévès', false),
('ROU','Roumanie', false),
('STP','Sao Tomé-et-Principe', false),
('ZAF','Afrique du Sud', false),
('ABW','Aruba', false),
('BEN','Bénin', false),
('BLR','Biélorussie', false),
('CYM','Îles Caïmans', false),
('GIB','Gibraltar', false),
('GNB','Guinée-Bissau', false),
('GRD','Grenade', false),
('IND','Inde', false),
('LBY','Libye', false),
('LCA','Sainte-Lucie', false),
('LVA','Lettonie', false),
('PRK','Corée du Nord', false),
('SSD','Soudan du Sud', false),
('TTO','Trinité et Tobago', false),
('ALB','Albanie', false),
('BTN','Bhoutan', false),
('CIV','Côte dIvoire', false),
('LKA','Sri Lanka', false),
('PAN','Panama', false),
('SYR','Syrie', false),
('UZB','Ouzbékistan', false),
('AUT','Autriche', false),
('EGY','Egypte', false),
('ERI','Erythrée', false),
('FRO','Îles Féroé', false),
('GNQ','Guinée-Équatoriale', false),
('GRL','Groenland', false),
('GUY','Guyana', false),
('LTU','Lituanie', false),
('MEX','Mexique', false),
('NOR','Norvège', false),
('RWA','Rwanda', false),
('SWZ','Eswatini', false),
('THA','Thaïlande', false),
('ARE','Emirats arabes unis', false),
('ESP','Espagne', false),
('GBR','Royaume-Uni', false),
('ISL','Islande', false),
('KEN','Kenya', false),
('LSO','Lesotho', false),
('NGA','Nigéria', false),
('PLW','Palaos', false),
('PNG','Papouasie-Nouvelle-Guinée', false),
('BFA','Burkina Faso', false),
('CHN','Chine', false),
('KHM','Cambodge', false),
('LBN','Liban', false),
('LIE','Liechtenstein', false),
('PRY','Paraguay', false),
('SVN','Slovénie', false),
('TON','Tonga', false),
('TUR','Turquie', false),
('TZA','Tanzanie', false),
('VGB','Îles Vierges britanniques', false)
SQL);
        $this->addSql('ALTER TABLE adresse DROP ligne3');
        $this->addSql('ALTER TABLE adresse DROP lieu_dit');
        $this->addSql('ALTER TABLE adresse DROP pays');
        $this->addSql('UPDATE personne_physique SET pays_naissance = NULL');
        $this->addSql('ALTER TABLE personne_physique ALTER pays_naissance TYPE VARCHAR(3)');
        $this->addSql('ALTER TABLE personne_physique ADD CONSTRAINT FK_5C2B29A2695C56A1 FOREIGN KEY (pays_naissance) REFERENCES geo_pays (code) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_5C2B29A2695C56A1 ON personne_physique (pays_naissance)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE personne_physique DROP CONSTRAINT FK_5C2B29A2695C56A1');
        $this->addSql('DROP TABLE geo_pays');
        $this->addSql('ALTER TABLE adresse ADD ligne3 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE adresse ADD lieu_dit VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE adresse ADD pays VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX IDX_5C2B29A2695C56A1');
        $this->addSql('ALTER TABLE personne_physique ALTER pays_naissance TYPE VARCHAR(255)');
    }
}
