<?php

namespace MonIndemnisationJustice\Service\DataGouv;

use Doctrine\ORM\EntityManagerInterface;
use MonIndemnisationJustice\Entity\GeoCodePostal;
use MonIndemnisationJustice\Entity\GeoCommune;
use MonIndemnisationJustice\Entity\GeoDepartement;

class ImporteurGeoCodePostal extends AbstractImporteurDataGouv
{
    //  Base officielle des codes postaux https://www.data.gouv.fr/fr/datasets/base-officielle-des-codes-postaux/
    private const RESOURCE_GEO_CODE_POSTAL = 'ca429285-b5a1-442b-8edf-8e6f68c304c9';
    protected $doublons = [];

    public function __construct(
        protected readonly EntityManagerInterface $em,
    ) {
        parent::__construct();
    }

    public function getResource(): string
    {
        return self::RESOURCE_GEO_CODE_POSTAL;
    }

    public function traiterEntree(array $entree): bool
    {
        $codeInsee = $entree['#Code_commune_INSEE'];
        $codePostal = $entree['Code_postal'];
        $identifiant = "$codePostal-$codeInsee";

        if (in_array($identifiant, $this->doublons)) {
            return false;
        }

        /** @var GeoCodePostal $code */
        $code = $this->em->getRepository(GeoCodePostal::class)->findOneBy([
            'commune' => $codeInsee,
            'codePostal' => $codePostal,
        ]);

        if (null === $code) {
            $commune = $this->em->getRepository(GeoCommune::class)->find($codeInsee);

            if (null === $commune) {
                $codeDepartement = substr($entree['#Code_commune_INSEE'], 0, str_starts_with($entree['#Code_commune_INSEE'], '97') ? 3 : 2);
                $departement = $this->em->getRepository(GeoDepartement::class)->find($codeDepartement);

                $commune = new GeoCommune()
                    ->setCode($codeInsee)
                    ->setNom($this->normaliserNom($entree['Nom_de_la_commune']))
                    ->setDepartement($departement);

                $this->em->persist($commune);
            }

            $code = new GeoCodePostal()
                ->setCodePostal($codePostal)
                ->setCommune($commune);

            $this->em->persist($code);

            $this->doublons[] = $identifiant;
        }

        return true;
    }

    protected function gererErreur(\Exception $e): void
    {
        $this->em->flush();
        parent::gererErreur($e); // TODO: Change the autogenerated stub
    }

    protected function apresImport(): void
    {
        $this->em->flush();
    }

    /**
     * "L ABERGEMENT CLEMENCIAT" => "L'Abergement-Clemenciat".
     * "MARSEILLE 16" => "Marseille"
     * "PONT L EVEQUE" => "Pont-l'eveque".
     */
    public function normaliserNom(string $nom): string
    {
        return array_reduce(
            explode(' ', $nom),
            function (string $nom, string $element) {
                // On élimine les valeurs numériques type numéro d'arrondissement
                if (is_numeric($element)) {
                    return $nom;
                }

                if ('L' === strtoupper($element)) {
                    return empty($nom) ? "L'" : "$nom-l'";
                }

                return "$nom".(str_ends_with($nom, "'") || empty($nom) ? '' : '-').ucfirst(strtolower($element));
            },
            ''
        );
    }
}
