controllers:
    resource:
        path: ../src/Controller
        namespace: App\Controller
    type: attribute


api_doc:
  path: 'https://www.google.com'
  schemes: [ 'https' ]
  host: 'www.google.com'