# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    MonIndemnisationJustice\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    MonIndemnisationJustice\Controller\SecurityController:
        $baseUrl: '%env(BASE_URL)%'

    MonIndemnisationJustice\Service\Mailer:
        $emailFrom: '%env(EMAIL_FROM)%'
        $emailFromLabel: '%env(EMAIL_FROM_LABEL)%'

    MonIndemnisationJustice\Service\BrisPorteManager:
        $courrielEquipe: '%env(PRECONTENTIEUX_COURRIEL_EQUIPE)%'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    Pentatrion\ViteBundle\Service\EntrypointsLookup: '@pentatrion_vite.entrypoints_lookup[_default]'

when@prod:
    services:
        Aws\S3\S3Client:
            arguments:
                - version: 'latest'
                  region: '%env(resolve:SCW_REGION)%'
                  endpoint: '%env(resolve:SCW_HOST)%'
                  use_path_style_endpoint: true
                  credentials:
                      key: '%env(resolve:SCW_ACCESS_KEY)%'
                      secret: '%env(resolve:SCW_SECRET_KEY)%'

when@develop:
    services:
        Aws\S3\S3Client:
            arguments:
                - version: 'latest'
                  region: '%env(resolve:SCW_REGION)%'
                  endpoint: '%env(resolve:SCW_HOST)%'
                  use_path_style_endpoint: true
                  credentials:
                      key: '%env(resolve:SCW_ACCESS_KEY)%'
                      secret: '%env(resolve:SCW_SECRET_KEY)%'