flysystem:
  storages:
    default.storage:
      adapter: 'local'
      options:
        directory: '%env(default:stockage_local:DOSSIER_STOCKAGE_LOCAL)%'

parameters:
  stockage_local: '%kernel.project_dir%/fichiers/dev'
