framework:
    # Trust reverse proxy headers
    trusted_proxies: 127.0.0.1, 172.16.0.0/12, 10.0.0.0/8
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']