name: "Build & push Docker image"

on:
  push:
    branches:
      - main
      - tech/dockerize-etreorg

jobs:
  build-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
          ref: main

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: pierrelemee
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push base Docker image
        uses: docker/build-push-action@v6
        with:
          file: .docker/php/Dockerfile
          push: true
          tags: pierrelemee/mij-frankenphp
          platforms: linux/amd64,linux/arm64