name: Deploy to app prod

on:
  workflow_run:
    workflows: [ "Test" ]
    types:
      - completed
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all history
          fetch-depth: 0
          ref: prod
      - name: Install clever tools
        run: |
          npm install -g clever-tools

      - name: Deploy to prod application
        env:
          CC_APP_ID: ${{ secrets.CC_APP_PROD_ID }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        run: |
          clever link $CC_APP_ID
          clever deploy --alias precontentieux-prod --force --same-commit-policy restart
