/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as RequisitionSerrurierRouteImport } from './../routes/requisition-serrurier'
import { Route as MonCompteRouteImport } from './../routes/mon-compte'
import { Route as LesDocumentsRouteImport } from './../routes/les-documents'
import { Route as FoireAuxQuestionsRouteImport } from './../routes/foire-aux-questions'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as BrisDePorteIndexRouteImport } from './../routes/bris-de-porte/index'
import { Route as BrisDePorteNouvelleDeclarationRouteImport } from './../routes/bris-de-porte/nouvelle-declaration'
import { Route as BrisDePorteMesDeclarationsRouteImport } from './../routes/bris-de-porte/mes-declarations'
import { Route as BrisDePorteReferenceIndexRouteImport } from './../routes/bris-de-porte/$reference/index'
import { Route as BrisDePorteReference3UsagerRouteImport } from './../routes/bris-de-porte/$reference/3-usager'
import { Route as BrisDePorteReference2ServiceEnqueteurRouteImport } from './../routes/bris-de-porte/$reference/2-service-enqueteur'
import { Route as BrisDePorteReference1BrisDePorteRouteImport } from './../routes/bris-de-porte/$reference/1-bris-de-porte'

const RequisitionSerrurierRoute = RequisitionSerrurierRouteImport.update({
  id: '/requisition-serrurier',
  path: '/requisition-serrurier',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteRoute = MonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const LesDocumentsRoute = LesDocumentsRouteImport.update({
  id: '/les-documents',
  path: '/les-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FoireAuxQuestionsRoute = FoireAuxQuestionsRouteImport.update({
  id: '/foire-aux-questions',
  path: '/foire-aux-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrisDePorteIndexRoute = BrisDePorteIndexRouteImport.update({
  id: '/bris-de-porte/',
  path: '/bris-de-porte/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrisDePorteNouvelleDeclarationRoute =
  BrisDePorteNouvelleDeclarationRouteImport.update({
    id: '/bris-de-porte/nouvelle-declaration',
    path: '/bris-de-porte/nouvelle-declaration',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrisDePorteMesDeclarationsRoute =
  BrisDePorteMesDeclarationsRouteImport.update({
    id: '/bris-de-porte/mes-declarations',
    path: '/bris-de-porte/mes-declarations',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrisDePorteReferenceIndexRoute =
  BrisDePorteReferenceIndexRouteImport.update({
    id: '/bris-de-porte/$reference/',
    path: '/bris-de-porte/$reference/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrisDePorteReference3UsagerRoute =
  BrisDePorteReference3UsagerRouteImport.update({
    id: '/bris-de-porte/$reference/3-usager',
    path: '/bris-de-porte/$reference/3-usager',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrisDePorteReference2ServiceEnqueteurRoute =
  BrisDePorteReference2ServiceEnqueteurRouteImport.update({
    id: '/bris-de-porte/$reference/2-service-enqueteur',
    path: '/bris-de-porte/$reference/2-service-enqueteur',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrisDePorteReference1BrisDePorteRoute =
  BrisDePorteReference1BrisDePorteRouteImport.update({
    id: '/bris-de-porte/$reference/1-bris-de-porte',
    path: '/bris-de-porte/$reference/1-bris-de-porte',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foire-aux-questions': typeof FoireAuxQuestionsRoute
  '/les-documents': typeof LesDocumentsRoute
  '/mon-compte': typeof MonCompteRoute
  '/requisition-serrurier': typeof RequisitionSerrurierRoute
  '/bris-de-porte/mes-declarations': typeof BrisDePorteMesDeclarationsRoute
  '/bris-de-porte/nouvelle-declaration': typeof BrisDePorteNouvelleDeclarationRoute
  '/bris-de-porte': typeof BrisDePorteIndexRoute
  '/bris-de-porte/$reference/1-bris-de-porte': typeof BrisDePorteReference1BrisDePorteRoute
  '/bris-de-porte/$reference/2-service-enqueteur': typeof BrisDePorteReference2ServiceEnqueteurRoute
  '/bris-de-porte/$reference/3-usager': typeof BrisDePorteReference3UsagerRoute
  '/bris-de-porte/$reference': typeof BrisDePorteReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foire-aux-questions': typeof FoireAuxQuestionsRoute
  '/les-documents': typeof LesDocumentsRoute
  '/mon-compte': typeof MonCompteRoute
  '/requisition-serrurier': typeof RequisitionSerrurierRoute
  '/bris-de-porte/mes-declarations': typeof BrisDePorteMesDeclarationsRoute
  '/bris-de-porte/nouvelle-declaration': typeof BrisDePorteNouvelleDeclarationRoute
  '/bris-de-porte': typeof BrisDePorteIndexRoute
  '/bris-de-porte/$reference/1-bris-de-porte': typeof BrisDePorteReference1BrisDePorteRoute
  '/bris-de-porte/$reference/2-service-enqueteur': typeof BrisDePorteReference2ServiceEnqueteurRoute
  '/bris-de-porte/$reference/3-usager': typeof BrisDePorteReference3UsagerRoute
  '/bris-de-porte/$reference': typeof BrisDePorteReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foire-aux-questions': typeof FoireAuxQuestionsRoute
  '/les-documents': typeof LesDocumentsRoute
  '/mon-compte': typeof MonCompteRoute
  '/requisition-serrurier': typeof RequisitionSerrurierRoute
  '/bris-de-porte/mes-declarations': typeof BrisDePorteMesDeclarationsRoute
  '/bris-de-porte/nouvelle-declaration': typeof BrisDePorteNouvelleDeclarationRoute
  '/bris-de-porte/': typeof BrisDePorteIndexRoute
  '/bris-de-porte/$reference/1-bris-de-porte': typeof BrisDePorteReference1BrisDePorteRoute
  '/bris-de-porte/$reference/2-service-enqueteur': typeof BrisDePorteReference2ServiceEnqueteurRoute
  '/bris-de-porte/$reference/3-usager': typeof BrisDePorteReference3UsagerRoute
  '/bris-de-porte/$reference/': typeof BrisDePorteReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/foire-aux-questions'
    | '/les-documents'
    | '/mon-compte'
    | '/requisition-serrurier'
    | '/bris-de-porte/mes-declarations'
    | '/bris-de-porte/nouvelle-declaration'
    | '/bris-de-porte'
    | '/bris-de-porte/$reference/1-bris-de-porte'
    | '/bris-de-porte/$reference/2-service-enqueteur'
    | '/bris-de-porte/$reference/3-usager'
    | '/bris-de-porte/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/foire-aux-questions'
    | '/les-documents'
    | '/mon-compte'
    | '/requisition-serrurier'
    | '/bris-de-porte/mes-declarations'
    | '/bris-de-porte/nouvelle-declaration'
    | '/bris-de-porte'
    | '/bris-de-porte/$reference/1-bris-de-porte'
    | '/bris-de-porte/$reference/2-service-enqueteur'
    | '/bris-de-porte/$reference/3-usager'
    | '/bris-de-porte/$reference'
  id:
    | '__root__'
    | '/'
    | '/foire-aux-questions'
    | '/les-documents'
    | '/mon-compte'
    | '/requisition-serrurier'
    | '/bris-de-porte/mes-declarations'
    | '/bris-de-porte/nouvelle-declaration'
    | '/bris-de-porte/'
    | '/bris-de-porte/$reference/1-bris-de-porte'
    | '/bris-de-porte/$reference/2-service-enqueteur'
    | '/bris-de-porte/$reference/3-usager'
    | '/bris-de-porte/$reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoireAuxQuestionsRoute: typeof FoireAuxQuestionsRoute
  LesDocumentsRoute: typeof LesDocumentsRoute
  MonCompteRoute: typeof MonCompteRoute
  RequisitionSerrurierRoute: typeof RequisitionSerrurierRoute
  BrisDePorteMesDeclarationsRoute: typeof BrisDePorteMesDeclarationsRoute
  BrisDePorteNouvelleDeclarationRoute: typeof BrisDePorteNouvelleDeclarationRoute
  BrisDePorteIndexRoute: typeof BrisDePorteIndexRoute
  BrisDePorteReference1BrisDePorteRoute: typeof BrisDePorteReference1BrisDePorteRoute
  BrisDePorteReference2ServiceEnqueteurRoute: typeof BrisDePorteReference2ServiceEnqueteurRoute
  BrisDePorteReference3UsagerRoute: typeof BrisDePorteReference3UsagerRoute
  BrisDePorteReferenceIndexRoute: typeof BrisDePorteReferenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/requisition-serrurier': {
      id: '/requisition-serrurier'
      path: '/requisition-serrurier'
      fullPath: '/requisition-serrurier'
      preLoaderRoute: typeof RequisitionSerrurierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte': {
      id: '/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof MonCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/les-documents': {
      id: '/les-documents'
      path: '/les-documents'
      fullPath: '/les-documents'
      preLoaderRoute: typeof LesDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foire-aux-questions': {
      id: '/foire-aux-questions'
      path: '/foire-aux-questions'
      fullPath: '/foire-aux-questions'
      preLoaderRoute: typeof FoireAuxQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bris-de-porte/': {
      id: '/bris-de-porte/'
      path: '/bris-de-porte'
      fullPath: '/bris-de-porte'
      preLoaderRoute: typeof BrisDePorteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bris-de-porte/nouvelle-declaration': {
      id: '/bris-de-porte/nouvelle-declaration'
      path: '/bris-de-porte/nouvelle-declaration'
      fullPath: '/bris-de-porte/nouvelle-declaration'
      preLoaderRoute: typeof BrisDePorteNouvelleDeclarationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bris-de-porte/mes-declarations': {
      id: '/bris-de-porte/mes-declarations'
      path: '/bris-de-porte/mes-declarations'
      fullPath: '/bris-de-porte/mes-declarations'
      preLoaderRoute: typeof BrisDePorteMesDeclarationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bris-de-porte/$reference/': {
      id: '/bris-de-porte/$reference/'
      path: '/bris-de-porte/$reference'
      fullPath: '/bris-de-porte/$reference'
      preLoaderRoute: typeof BrisDePorteReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bris-de-porte/$reference/3-usager': {
      id: '/bris-de-porte/$reference/3-usager'
      path: '/bris-de-porte/$reference/3-usager'
      fullPath: '/bris-de-porte/$reference/3-usager'
      preLoaderRoute: typeof BrisDePorteReference3UsagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bris-de-porte/$reference/2-service-enqueteur': {
      id: '/bris-de-porte/$reference/2-service-enqueteur'
      path: '/bris-de-porte/$reference/2-service-enqueteur'
      fullPath: '/bris-de-porte/$reference/2-service-enqueteur'
      preLoaderRoute: typeof BrisDePorteReference2ServiceEnqueteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bris-de-porte/$reference/1-bris-de-porte': {
      id: '/bris-de-porte/$reference/1-bris-de-porte'
      path: '/bris-de-porte/$reference/1-bris-de-porte'
      fullPath: '/bris-de-porte/$reference/1-bris-de-porte'
      preLoaderRoute: typeof BrisDePorteReference1BrisDePorteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoireAuxQuestionsRoute: FoireAuxQuestionsRoute,
  LesDocumentsRoute: LesDocumentsRoute,
  MonCompteRoute: MonCompteRoute,
  RequisitionSerrurierRoute: RequisitionSerrurierRoute,
  BrisDePorteMesDeclarationsRoute: BrisDePorteMesDeclarationsRoute,
  BrisDePorteNouvelleDeclarationRoute: BrisDePorteNouvelleDeclarationRoute,
  BrisDePorteIndexRoute: BrisDePorteIndexRoute,
  BrisDePorteReference1BrisDePorteRoute: BrisDePorteReference1BrisDePorteRoute,
  BrisDePorteReference2ServiceEnqueteurRoute:
    BrisDePorteReference2ServiceEnqueteurRoute,
  BrisDePorteReference3UsagerRoute: BrisDePorteReference3UsagerRoute,
  BrisDePorteReferenceIndexRoute: BrisDePorteReferenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
