/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as AgentFdoIndexRouteImport } from './../routes/agent/fdo/index'
import { Route as AgentFdoRequisitionSerrurierRouteImport } from './../routes/agent/fdo/requisition-serrurier'
import { Route as AgentFdoLesDocumentsRouteImport } from './../routes/agent/fdo/les-documents'
import { Route as AgentFdoFoireAuxQuestionsRouteImport } from './../routes/agent/fdo/foire-aux-questions'
import { Route as AgentFdoBrisDePorteIndexRouteImport } from './../routes/agent/fdo/bris-de-porte/index'
import { Route as AgentFdoBrisDePorteNouvelleDeclarationRouteImport } from './../routes/agent/fdo/bris-de-porte/nouvelle-declaration'
import { Route as AgentFdoBrisDePorteMesDeclarationsRouteImport } from './../routes/agent/fdo/bris-de-porte/mes-declarations'
import { Route as AgentFdoBrisDePorteReferenceIndexRouteImport } from './../routes/agent/fdo/bris-de-porte/$reference/index'
import { Route as AgentFdoBrisDePorteReference3UsagerRouteImport } from './../routes/agent/fdo/bris-de-porte/$reference/3-usager'
import { Route as AgentFdoBrisDePorteReference2ServiceEnqueteurRouteImport } from './../routes/agent/fdo/bris-de-porte/$reference/2-service-enqueteur'
import { Route as AgentFdoBrisDePorteReference1BrisDePorteRouteImport } from './../routes/agent/fdo/bris-de-porte/$reference/1-bris-de-porte'

const AgentFdoIndexRoute = AgentFdoIndexRouteImport.update({
  id: '/agent/fdo/',
  path: '/agent/fdo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentFdoRequisitionSerrurierRoute =
  AgentFdoRequisitionSerrurierRouteImport.update({
    id: '/agent/fdo/requisition-serrurier',
    path: '/agent/fdo/requisition-serrurier',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoLesDocumentsRoute = AgentFdoLesDocumentsRouteImport.update({
  id: '/agent/fdo/les-documents',
  path: '/agent/fdo/les-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentFdoFoireAuxQuestionsRoute =
  AgentFdoFoireAuxQuestionsRouteImport.update({
    id: '/agent/fdo/foire-aux-questions',
    path: '/agent/fdo/foire-aux-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoBrisDePorteIndexRoute =
  AgentFdoBrisDePorteIndexRouteImport.update({
    id: '/agent/fdo/bris-de-porte/',
    path: '/agent/fdo/bris-de-porte/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoBrisDePorteNouvelleDeclarationRoute =
  AgentFdoBrisDePorteNouvelleDeclarationRouteImport.update({
    id: '/agent/fdo/bris-de-porte/nouvelle-declaration',
    path: '/agent/fdo/bris-de-porte/nouvelle-declaration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoBrisDePorteMesDeclarationsRoute =
  AgentFdoBrisDePorteMesDeclarationsRouteImport.update({
    id: '/agent/fdo/bris-de-porte/mes-declarations',
    path: '/agent/fdo/bris-de-porte/mes-declarations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoBrisDePorteReferenceIndexRoute =
  AgentFdoBrisDePorteReferenceIndexRouteImport.update({
    id: '/agent/fdo/bris-de-porte/$reference/',
    path: '/agent/fdo/bris-de-porte/$reference/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoBrisDePorteReference3UsagerRoute =
  AgentFdoBrisDePorteReference3UsagerRouteImport.update({
    id: '/agent/fdo/bris-de-porte/$reference/3-usager',
    path: '/agent/fdo/bris-de-porte/$reference/3-usager',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoBrisDePorteReference2ServiceEnqueteurRoute =
  AgentFdoBrisDePorteReference2ServiceEnqueteurRouteImport.update({
    id: '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur',
    path: '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoBrisDePorteReference1BrisDePorteRoute =
  AgentFdoBrisDePorteReference1BrisDePorteRouteImport.update({
    id: '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte',
    path: '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/agent/fdo/foire-aux-questions': typeof AgentFdoFoireAuxQuestionsRoute
  '/agent/fdo/les-documents': typeof AgentFdoLesDocumentsRoute
  '/agent/fdo/requisition-serrurier': typeof AgentFdoRequisitionSerrurierRoute
  '/agent/fdo': typeof AgentFdoIndexRoute
  '/agent/fdo/bris-de-porte/mes-declarations': typeof AgentFdoBrisDePorteMesDeclarationsRoute
  '/agent/fdo/bris-de-porte/nouvelle-declaration': typeof AgentFdoBrisDePorteNouvelleDeclarationRoute
  '/agent/fdo/bris-de-porte': typeof AgentFdoBrisDePorteIndexRoute
  '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte': typeof AgentFdoBrisDePorteReference1BrisDePorteRoute
  '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur': typeof AgentFdoBrisDePorteReference2ServiceEnqueteurRoute
  '/agent/fdo/bris-de-porte/$reference/3-usager': typeof AgentFdoBrisDePorteReference3UsagerRoute
  '/agent/fdo/bris-de-porte/$reference': typeof AgentFdoBrisDePorteReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/agent/fdo/foire-aux-questions': typeof AgentFdoFoireAuxQuestionsRoute
  '/agent/fdo/les-documents': typeof AgentFdoLesDocumentsRoute
  '/agent/fdo/requisition-serrurier': typeof AgentFdoRequisitionSerrurierRoute
  '/agent/fdo': typeof AgentFdoIndexRoute
  '/agent/fdo/bris-de-porte/mes-declarations': typeof AgentFdoBrisDePorteMesDeclarationsRoute
  '/agent/fdo/bris-de-porte/nouvelle-declaration': typeof AgentFdoBrisDePorteNouvelleDeclarationRoute
  '/agent/fdo/bris-de-porte': typeof AgentFdoBrisDePorteIndexRoute
  '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte': typeof AgentFdoBrisDePorteReference1BrisDePorteRoute
  '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur': typeof AgentFdoBrisDePorteReference2ServiceEnqueteurRoute
  '/agent/fdo/bris-de-porte/$reference/3-usager': typeof AgentFdoBrisDePorteReference3UsagerRoute
  '/agent/fdo/bris-de-porte/$reference': typeof AgentFdoBrisDePorteReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/agent/fdo/foire-aux-questions': typeof AgentFdoFoireAuxQuestionsRoute
  '/agent/fdo/les-documents': typeof AgentFdoLesDocumentsRoute
  '/agent/fdo/requisition-serrurier': typeof AgentFdoRequisitionSerrurierRoute
  '/agent/fdo/': typeof AgentFdoIndexRoute
  '/agent/fdo/bris-de-porte/mes-declarations': typeof AgentFdoBrisDePorteMesDeclarationsRoute
  '/agent/fdo/bris-de-porte/nouvelle-declaration': typeof AgentFdoBrisDePorteNouvelleDeclarationRoute
  '/agent/fdo/bris-de-porte/': typeof AgentFdoBrisDePorteIndexRoute
  '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte': typeof AgentFdoBrisDePorteReference1BrisDePorteRoute
  '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur': typeof AgentFdoBrisDePorteReference2ServiceEnqueteurRoute
  '/agent/fdo/bris-de-porte/$reference/3-usager': typeof AgentFdoBrisDePorteReference3UsagerRoute
  '/agent/fdo/bris-de-porte/$reference/': typeof AgentFdoBrisDePorteReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agent/fdo/foire-aux-questions'
    | '/agent/fdo/les-documents'
    | '/agent/fdo/requisition-serrurier'
    | '/agent/fdo'
    | '/agent/fdo/bris-de-porte/mes-declarations'
    | '/agent/fdo/bris-de-porte/nouvelle-declaration'
    | '/agent/fdo/bris-de-porte'
    | '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte'
    | '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur'
    | '/agent/fdo/bris-de-porte/$reference/3-usager'
    | '/agent/fdo/bris-de-porte/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agent/fdo/foire-aux-questions'
    | '/agent/fdo/les-documents'
    | '/agent/fdo/requisition-serrurier'
    | '/agent/fdo'
    | '/agent/fdo/bris-de-porte/mes-declarations'
    | '/agent/fdo/bris-de-porte/nouvelle-declaration'
    | '/agent/fdo/bris-de-porte'
    | '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte'
    | '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur'
    | '/agent/fdo/bris-de-porte/$reference/3-usager'
    | '/agent/fdo/bris-de-porte/$reference'
  id:
    | '__root__'
    | '/agent/fdo/foire-aux-questions'
    | '/agent/fdo/les-documents'
    | '/agent/fdo/requisition-serrurier'
    | '/agent/fdo/'
    | '/agent/fdo/bris-de-porte/mes-declarations'
    | '/agent/fdo/bris-de-porte/nouvelle-declaration'
    | '/agent/fdo/bris-de-porte/'
    | '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte'
    | '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur'
    | '/agent/fdo/bris-de-porte/$reference/3-usager'
    | '/agent/fdo/bris-de-porte/$reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AgentFdoFoireAuxQuestionsRoute: typeof AgentFdoFoireAuxQuestionsRoute
  AgentFdoLesDocumentsRoute: typeof AgentFdoLesDocumentsRoute
  AgentFdoRequisitionSerrurierRoute: typeof AgentFdoRequisitionSerrurierRoute
  AgentFdoIndexRoute: typeof AgentFdoIndexRoute
  AgentFdoBrisDePorteMesDeclarationsRoute: typeof AgentFdoBrisDePorteMesDeclarationsRoute
  AgentFdoBrisDePorteNouvelleDeclarationRoute: typeof AgentFdoBrisDePorteNouvelleDeclarationRoute
  AgentFdoBrisDePorteIndexRoute: typeof AgentFdoBrisDePorteIndexRoute
  AgentFdoBrisDePorteReference1BrisDePorteRoute: typeof AgentFdoBrisDePorteReference1BrisDePorteRoute
  AgentFdoBrisDePorteReference2ServiceEnqueteurRoute: typeof AgentFdoBrisDePorteReference2ServiceEnqueteurRoute
  AgentFdoBrisDePorteReference3UsagerRoute: typeof AgentFdoBrisDePorteReference3UsagerRoute
  AgentFdoBrisDePorteReferenceIndexRoute: typeof AgentFdoBrisDePorteReferenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agent/fdo/': {
      id: '/agent/fdo/'
      path: '/agent/fdo'
      fullPath: '/agent/fdo'
      preLoaderRoute: typeof AgentFdoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/requisition-serrurier': {
      id: '/agent/fdo/requisition-serrurier'
      path: '/agent/fdo/requisition-serrurier'
      fullPath: '/agent/fdo/requisition-serrurier'
      preLoaderRoute: typeof AgentFdoRequisitionSerrurierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/les-documents': {
      id: '/agent/fdo/les-documents'
      path: '/agent/fdo/les-documents'
      fullPath: '/agent/fdo/les-documents'
      preLoaderRoute: typeof AgentFdoLesDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/foire-aux-questions': {
      id: '/agent/fdo/foire-aux-questions'
      path: '/agent/fdo/foire-aux-questions'
      fullPath: '/agent/fdo/foire-aux-questions'
      preLoaderRoute: typeof AgentFdoFoireAuxQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/bris-de-porte/': {
      id: '/agent/fdo/bris-de-porte/'
      path: '/agent/fdo/bris-de-porte'
      fullPath: '/agent/fdo/bris-de-porte'
      preLoaderRoute: typeof AgentFdoBrisDePorteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/bris-de-porte/nouvelle-declaration': {
      id: '/agent/fdo/bris-de-porte/nouvelle-declaration'
      path: '/agent/fdo/bris-de-porte/nouvelle-declaration'
      fullPath: '/agent/fdo/bris-de-porte/nouvelle-declaration'
      preLoaderRoute: typeof AgentFdoBrisDePorteNouvelleDeclarationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/bris-de-porte/mes-declarations': {
      id: '/agent/fdo/bris-de-porte/mes-declarations'
      path: '/agent/fdo/bris-de-porte/mes-declarations'
      fullPath: '/agent/fdo/bris-de-porte/mes-declarations'
      preLoaderRoute: typeof AgentFdoBrisDePorteMesDeclarationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/bris-de-porte/$reference/': {
      id: '/agent/fdo/bris-de-porte/$reference/'
      path: '/agent/fdo/bris-de-porte/$reference'
      fullPath: '/agent/fdo/bris-de-porte/$reference'
      preLoaderRoute: typeof AgentFdoBrisDePorteReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/bris-de-porte/$reference/3-usager': {
      id: '/agent/fdo/bris-de-porte/$reference/3-usager'
      path: '/agent/fdo/bris-de-porte/$reference/3-usager'
      fullPath: '/agent/fdo/bris-de-porte/$reference/3-usager'
      preLoaderRoute: typeof AgentFdoBrisDePorteReference3UsagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur': {
      id: '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur'
      path: '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur'
      fullPath: '/agent/fdo/bris-de-porte/$reference/2-service-enqueteur'
      preLoaderRoute: typeof AgentFdoBrisDePorteReference2ServiceEnqueteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte': {
      id: '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte'
      path: '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte'
      fullPath: '/agent/fdo/bris-de-porte/$reference/1-bris-de-porte'
      preLoaderRoute: typeof AgentFdoBrisDePorteReference1BrisDePorteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AgentFdoFoireAuxQuestionsRoute: AgentFdoFoireAuxQuestionsRoute,
  AgentFdoLesDocumentsRoute: AgentFdoLesDocumentsRoute,
  AgentFdoRequisitionSerrurierRoute: AgentFdoRequisitionSerrurierRoute,
  AgentFdoIndexRoute: AgentFdoIndexRoute,
  AgentFdoBrisDePorteMesDeclarationsRoute:
    AgentFdoBrisDePorteMesDeclarationsRoute,
  AgentFdoBrisDePorteNouvelleDeclarationRoute:
    AgentFdoBrisDePorteNouvelleDeclarationRoute,
  AgentFdoBrisDePorteIndexRoute: AgentFdoBrisDePorteIndexRoute,
  AgentFdoBrisDePorteReference1BrisDePorteRoute:
    AgentFdoBrisDePorteReference1BrisDePorteRoute,
  AgentFdoBrisDePorteReference2ServiceEnqueteurRoute:
    AgentFdoBrisDePorteReference2ServiceEnqueteurRoute,
  AgentFdoBrisDePorteReference3UsagerRoute:
    AgentFdoBrisDePorteReference3UsagerRoute,
  AgentFdoBrisDePorteReferenceIndexRoute:
    AgentFdoBrisDePorteReferenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
