/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as AgentFdoIndexRouteImport } from './../routes/agent/fdo/index'
import { Route as AgentFdoRequisitionSerrurierRouteImport } from './../routes/agent/fdo/requisition-serrurier'
import { Route as AgentFdoFoireAuxQuestionsRouteImport } from './../routes/agent/fdo/foire-aux-questions'
import { Route as AgentFdoErreurOperationnelleIndexRouteImport } from './../routes/agent/fdo/erreur-operationnelle/index'
import { Route as AgentFdoErreurOperationnelleNouvelleDeclarationRouteImport } from './../routes/agent/fdo/erreur-operationnelle/nouvelle-declaration'
import { Route as AgentFdoErreurOperationnelleMesDeclarationsRouteImport } from './../routes/agent/fdo/erreur-operationnelle/mes-declarations'
import { Route as AgentFdoErreurOperationnelleReferenceIndexRouteImport } from './../routes/agent/fdo/erreur-operationnelle/$reference/index'
import { Route as AgentFdoErreurOperationnelleReference3RequerantRouteImport } from './../routes/agent/fdo/erreur-operationnelle/$reference/3-requerant'
import { Route as AgentFdoErreurOperationnelleReference2ComplementRouteImport } from './../routes/agent/fdo/erreur-operationnelle/$reference/2-complement'
import { Route as AgentFdoErreurOperationnelleReference1OperationRouteImport } from './../routes/agent/fdo/erreur-operationnelle/$reference/1-operation'

const AgentFdoIndexRoute = AgentFdoIndexRouteImport.update({
  id: '/agent/fdo/',
  path: '/agent/fdo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentFdoRequisitionSerrurierRoute =
  AgentFdoRequisitionSerrurierRouteImport.update({
    id: '/agent/fdo/requisition-serrurier',
    path: '/agent/fdo/requisition-serrurier',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoFoireAuxQuestionsRoute =
  AgentFdoFoireAuxQuestionsRouteImport.update({
    id: '/agent/fdo/foire-aux-questions',
    path: '/agent/fdo/foire-aux-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoErreurOperationnelleIndexRoute =
  AgentFdoErreurOperationnelleIndexRouteImport.update({
    id: '/agent/fdo/erreur-operationnelle/',
    path: '/agent/fdo/erreur-operationnelle/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoErreurOperationnelleNouvelleDeclarationRoute =
  AgentFdoErreurOperationnelleNouvelleDeclarationRouteImport.update({
    id: '/agent/fdo/erreur-operationnelle/nouvelle-declaration',
    path: '/agent/fdo/erreur-operationnelle/nouvelle-declaration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoErreurOperationnelleMesDeclarationsRoute =
  AgentFdoErreurOperationnelleMesDeclarationsRouteImport.update({
    id: '/agent/fdo/erreur-operationnelle/mes-declarations',
    path: '/agent/fdo/erreur-operationnelle/mes-declarations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoErreurOperationnelleReferenceIndexRoute =
  AgentFdoErreurOperationnelleReferenceIndexRouteImport.update({
    id: '/agent/fdo/erreur-operationnelle/$reference/',
    path: '/agent/fdo/erreur-operationnelle/$reference/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoErreurOperationnelleReference3RequerantRoute =
  AgentFdoErreurOperationnelleReference3RequerantRouteImport.update({
    id: '/agent/fdo/erreur-operationnelle/$reference/3-requerant',
    path: '/agent/fdo/erreur-operationnelle/$reference/3-requerant',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoErreurOperationnelleReference2ComplementRoute =
  AgentFdoErreurOperationnelleReference2ComplementRouteImport.update({
    id: '/agent/fdo/erreur-operationnelle/$reference/2-complement',
    path: '/agent/fdo/erreur-operationnelle/$reference/2-complement',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentFdoErreurOperationnelleReference1OperationRoute =
  AgentFdoErreurOperationnelleReference1OperationRouteImport.update({
    id: '/agent/fdo/erreur-operationnelle/$reference/1-operation',
    path: '/agent/fdo/erreur-operationnelle/$reference/1-operation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/agent/fdo/foire-aux-questions': typeof AgentFdoFoireAuxQuestionsRoute
  '/agent/fdo/requisition-serrurier': typeof AgentFdoRequisitionSerrurierRoute
  '/agent/fdo': typeof AgentFdoIndexRoute
  '/agent/fdo/erreur-operationnelle/mes-declarations': typeof AgentFdoErreurOperationnelleMesDeclarationsRoute
  '/agent/fdo/erreur-operationnelle/nouvelle-declaration': typeof AgentFdoErreurOperationnelleNouvelleDeclarationRoute
  '/agent/fdo/erreur-operationnelle': typeof AgentFdoErreurOperationnelleIndexRoute
  '/agent/fdo/erreur-operationnelle/$reference/1-operation': typeof AgentFdoErreurOperationnelleReference1OperationRoute
  '/agent/fdo/erreur-operationnelle/$reference/2-complement': typeof AgentFdoErreurOperationnelleReference2ComplementRoute
  '/agent/fdo/erreur-operationnelle/$reference/3-requerant': typeof AgentFdoErreurOperationnelleReference3RequerantRoute
  '/agent/fdo/erreur-operationnelle/$reference': typeof AgentFdoErreurOperationnelleReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/agent/fdo/foire-aux-questions': typeof AgentFdoFoireAuxQuestionsRoute
  '/agent/fdo/requisition-serrurier': typeof AgentFdoRequisitionSerrurierRoute
  '/agent/fdo': typeof AgentFdoIndexRoute
  '/agent/fdo/erreur-operationnelle/mes-declarations': typeof AgentFdoErreurOperationnelleMesDeclarationsRoute
  '/agent/fdo/erreur-operationnelle/nouvelle-declaration': typeof AgentFdoErreurOperationnelleNouvelleDeclarationRoute
  '/agent/fdo/erreur-operationnelle': typeof AgentFdoErreurOperationnelleIndexRoute
  '/agent/fdo/erreur-operationnelle/$reference/1-operation': typeof AgentFdoErreurOperationnelleReference1OperationRoute
  '/agent/fdo/erreur-operationnelle/$reference/2-complement': typeof AgentFdoErreurOperationnelleReference2ComplementRoute
  '/agent/fdo/erreur-operationnelle/$reference/3-requerant': typeof AgentFdoErreurOperationnelleReference3RequerantRoute
  '/agent/fdo/erreur-operationnelle/$reference': typeof AgentFdoErreurOperationnelleReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/agent/fdo/foire-aux-questions': typeof AgentFdoFoireAuxQuestionsRoute
  '/agent/fdo/requisition-serrurier': typeof AgentFdoRequisitionSerrurierRoute
  '/agent/fdo/': typeof AgentFdoIndexRoute
  '/agent/fdo/erreur-operationnelle/mes-declarations': typeof AgentFdoErreurOperationnelleMesDeclarationsRoute
  '/agent/fdo/erreur-operationnelle/nouvelle-declaration': typeof AgentFdoErreurOperationnelleNouvelleDeclarationRoute
  '/agent/fdo/erreur-operationnelle/': typeof AgentFdoErreurOperationnelleIndexRoute
  '/agent/fdo/erreur-operationnelle/$reference/1-operation': typeof AgentFdoErreurOperationnelleReference1OperationRoute
  '/agent/fdo/erreur-operationnelle/$reference/2-complement': typeof AgentFdoErreurOperationnelleReference2ComplementRoute
  '/agent/fdo/erreur-operationnelle/$reference/3-requerant': typeof AgentFdoErreurOperationnelleReference3RequerantRoute
  '/agent/fdo/erreur-operationnelle/$reference/': typeof AgentFdoErreurOperationnelleReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agent/fdo/foire-aux-questions'
    | '/agent/fdo/requisition-serrurier'
    | '/agent/fdo'
    | '/agent/fdo/erreur-operationnelle/mes-declarations'
    | '/agent/fdo/erreur-operationnelle/nouvelle-declaration'
    | '/agent/fdo/erreur-operationnelle'
    | '/agent/fdo/erreur-operationnelle/$reference/1-operation'
    | '/agent/fdo/erreur-operationnelle/$reference/2-complement'
    | '/agent/fdo/erreur-operationnelle/$reference/3-requerant'
    | '/agent/fdo/erreur-operationnelle/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agent/fdo/foire-aux-questions'
    | '/agent/fdo/requisition-serrurier'
    | '/agent/fdo'
    | '/agent/fdo/erreur-operationnelle/mes-declarations'
    | '/agent/fdo/erreur-operationnelle/nouvelle-declaration'
    | '/agent/fdo/erreur-operationnelle'
    | '/agent/fdo/erreur-operationnelle/$reference/1-operation'
    | '/agent/fdo/erreur-operationnelle/$reference/2-complement'
    | '/agent/fdo/erreur-operationnelle/$reference/3-requerant'
    | '/agent/fdo/erreur-operationnelle/$reference'
  id:
    | '__root__'
    | '/agent/fdo/foire-aux-questions'
    | '/agent/fdo/requisition-serrurier'
    | '/agent/fdo/'
    | '/agent/fdo/erreur-operationnelle/mes-declarations'
    | '/agent/fdo/erreur-operationnelle/nouvelle-declaration'
    | '/agent/fdo/erreur-operationnelle/'
    | '/agent/fdo/erreur-operationnelle/$reference/1-operation'
    | '/agent/fdo/erreur-operationnelle/$reference/2-complement'
    | '/agent/fdo/erreur-operationnelle/$reference/3-requerant'
    | '/agent/fdo/erreur-operationnelle/$reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AgentFdoFoireAuxQuestionsRoute: typeof AgentFdoFoireAuxQuestionsRoute
  AgentFdoRequisitionSerrurierRoute: typeof AgentFdoRequisitionSerrurierRoute
  AgentFdoIndexRoute: typeof AgentFdoIndexRoute
  AgentFdoErreurOperationnelleMesDeclarationsRoute: typeof AgentFdoErreurOperationnelleMesDeclarationsRoute
  AgentFdoErreurOperationnelleNouvelleDeclarationRoute: typeof AgentFdoErreurOperationnelleNouvelleDeclarationRoute
  AgentFdoErreurOperationnelleIndexRoute: typeof AgentFdoErreurOperationnelleIndexRoute
  AgentFdoErreurOperationnelleReference1OperationRoute: typeof AgentFdoErreurOperationnelleReference1OperationRoute
  AgentFdoErreurOperationnelleReference2ComplementRoute: typeof AgentFdoErreurOperationnelleReference2ComplementRoute
  AgentFdoErreurOperationnelleReference3RequerantRoute: typeof AgentFdoErreurOperationnelleReference3RequerantRoute
  AgentFdoErreurOperationnelleReferenceIndexRoute: typeof AgentFdoErreurOperationnelleReferenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agent/fdo/': {
      id: '/agent/fdo/'
      path: '/agent/fdo'
      fullPath: '/agent/fdo'
      preLoaderRoute: typeof AgentFdoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/requisition-serrurier': {
      id: '/agent/fdo/requisition-serrurier'
      path: '/agent/fdo/requisition-serrurier'
      fullPath: '/agent/fdo/requisition-serrurier'
      preLoaderRoute: typeof AgentFdoRequisitionSerrurierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/foire-aux-questions': {
      id: '/agent/fdo/foire-aux-questions'
      path: '/agent/fdo/foire-aux-questions'
      fullPath: '/agent/fdo/foire-aux-questions'
      preLoaderRoute: typeof AgentFdoFoireAuxQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/erreur-operationnelle/': {
      id: '/agent/fdo/erreur-operationnelle/'
      path: '/agent/fdo/erreur-operationnelle'
      fullPath: '/agent/fdo/erreur-operationnelle'
      preLoaderRoute: typeof AgentFdoErreurOperationnelleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/erreur-operationnelle/nouvelle-declaration': {
      id: '/agent/fdo/erreur-operationnelle/nouvelle-declaration'
      path: '/agent/fdo/erreur-operationnelle/nouvelle-declaration'
      fullPath: '/agent/fdo/erreur-operationnelle/nouvelle-declaration'
      preLoaderRoute: typeof AgentFdoErreurOperationnelleNouvelleDeclarationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/erreur-operationnelle/mes-declarations': {
      id: '/agent/fdo/erreur-operationnelle/mes-declarations'
      path: '/agent/fdo/erreur-operationnelle/mes-declarations'
      fullPath: '/agent/fdo/erreur-operationnelle/mes-declarations'
      preLoaderRoute: typeof AgentFdoErreurOperationnelleMesDeclarationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/erreur-operationnelle/$reference/': {
      id: '/agent/fdo/erreur-operationnelle/$reference/'
      path: '/agent/fdo/erreur-operationnelle/$reference'
      fullPath: '/agent/fdo/erreur-operationnelle/$reference'
      preLoaderRoute: typeof AgentFdoErreurOperationnelleReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/erreur-operationnelle/$reference/3-requerant': {
      id: '/agent/fdo/erreur-operationnelle/$reference/3-requerant'
      path: '/agent/fdo/erreur-operationnelle/$reference/3-requerant'
      fullPath: '/agent/fdo/erreur-operationnelle/$reference/3-requerant'
      preLoaderRoute: typeof AgentFdoErreurOperationnelleReference3RequerantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/erreur-operationnelle/$reference/2-complement': {
      id: '/agent/fdo/erreur-operationnelle/$reference/2-complement'
      path: '/agent/fdo/erreur-operationnelle/$reference/2-complement'
      fullPath: '/agent/fdo/erreur-operationnelle/$reference/2-complement'
      preLoaderRoute: typeof AgentFdoErreurOperationnelleReference2ComplementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/fdo/erreur-operationnelle/$reference/1-operation': {
      id: '/agent/fdo/erreur-operationnelle/$reference/1-operation'
      path: '/agent/fdo/erreur-operationnelle/$reference/1-operation'
      fullPath: '/agent/fdo/erreur-operationnelle/$reference/1-operation'
      preLoaderRoute: typeof AgentFdoErreurOperationnelleReference1OperationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AgentFdoFoireAuxQuestionsRoute: AgentFdoFoireAuxQuestionsRoute,
  AgentFdoRequisitionSerrurierRoute: AgentFdoRequisitionSerrurierRoute,
  AgentFdoIndexRoute: AgentFdoIndexRoute,
  AgentFdoErreurOperationnelleMesDeclarationsRoute:
    AgentFdoErreurOperationnelleMesDeclarationsRoute,
  AgentFdoErreurOperationnelleNouvelleDeclarationRoute:
    AgentFdoErreurOperationnelleNouvelleDeclarationRoute,
  AgentFdoErreurOperationnelleIndexRoute:
    AgentFdoErreurOperationnelleIndexRoute,
  AgentFdoErreurOperationnelleReference1OperationRoute:
    AgentFdoErreurOperationnelleReference1OperationRoute,
  AgentFdoErreurOperationnelleReference2ComplementRoute:
    AgentFdoErreurOperationnelleReference2ComplementRoute,
  AgentFdoErreurOperationnelleReference3RequerantRoute:
    AgentFdoErreurOperationnelleReference3RequerantRoute,
  AgentFdoErreurOperationnelleReferenceIndexRoute:
    AgentFdoErreurOperationnelleReferenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
